"""
Curated catalog of humanoid robot companies and flagship products.

Used by humanoid discovery to seed ``humanoid_benchmarks`` beyond the original
11-robot seed set. Sources: HEIR 2026, manufacturer sites, trade show lists,
and industry coverage (2024–2026).
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

# Each entry: name, vendor, optional model_slug, product_url, status, country, specs (partial)
HUMANOID_CATALOG: List[Dict[str, Any]] = [
    # ── Tier 1 — commercially visible ────────────────────────────────────────
    {"name": "Unitree G1", "vendor": "Unitree Robotics", "model_slug": "unitree-g1", "product_url": "https://www.unitree.com/g1", "status": "available", "country": "China"},
    {"name": "Unitree H1", "vendor": "Unitree Robotics", "model_slug": "unitree-h1", "product_url": "https://www.unitree.com/h1", "status": "available", "country": "China"},
    {"name": "Unitree R1", "vendor": "Unitree Robotics", "model_slug": "unitree-r1", "product_url": "https://www.unitree.com", "status": "pilot", "country": "China"},
    {"name": "Figure 02", "vendor": "Figure AI", "model_slug": "figure-02", "product_url": "https://www.figure.ai", "status": "pilot", "country": "USA"},
    {"name": "Figure 01", "vendor": "Figure AI", "model_slug": "figure-01", "product_url": "https://www.figure.ai", "status": "research", "country": "USA"},
    {"name": "Agility Digit", "vendor": "Agility Robotics", "model_slug": "agility-digit", "product_url": "https://agilityrobotics.com/digit", "status": "available", "country": "USA"},
    {"name": "Tesla Optimus Gen 2", "vendor": "Tesla", "model_slug": "tesla-optimus-gen2", "product_url": "https://www.tesla.com/optimus", "status": "pilot", "country": "USA"},
    {"name": "Boston Dynamics Atlas", "vendor": "Boston Dynamics", "model_slug": "boston-dynamics-atlas", "product_url": "https://bostondynamics.com/atlas", "status": "pilot", "country": "USA"},
    {"name": "Apptronik Apollo", "vendor": "Apptronik", "model_slug": "apptronik-apollo", "product_url": "https://apptronik.com/apollo", "status": "pilot", "country": "USA"},
    {"name": "1X NEO", "vendor": "1X Technologies", "model_slug": "1x-neo", "product_url": "https://www.1x.tech/neo", "status": "pilot", "country": "USA"},
    {"name": "1X Eve", "vendor": "1X Technologies", "model_slug": "1x-eve", "product_url": "https://www.1x.tech", "status": "pilot", "country": "Norway"},
    {"name": "Sanctuary Phoenix", "vendor": "Sanctuary AI", "model_slug": "sanctuary-phoenix", "product_url": "https://sanctuary.ai", "status": "pilot", "country": "Canada"},
    {"name": "Agibot A2", "vendor": "Agibot (Zhiyuan Robotics)", "model_slug": "agibot-a2", "product_url": "https://agibot.com", "status": "available", "country": "China"},
    {"name": "Agibot G5", "vendor": "Agibot (Zhiyuan Robotics)", "model_slug": "agibot-g5", "product_url": "https://agibot.com", "status": "pilot", "country": "China"},
    {"name": "UBTECH Walker X", "vendor": "UBTECH Robotics", "model_slug": "ubtech-walker-x", "product_url": "https://www.ubtrobot.com/walker", "status": "available", "country": "China"},
    {"name": "UBTECH Walker S", "vendor": "UBTECH Robotics", "model_slug": "ubtech-walker-s", "product_url": "https://www.ubtrobot.com", "status": "pilot", "country": "China"},
    {"name": "EngineAI PM01", "vendor": "EngineAI", "model_slug": "engineai-pm01", "product_url": "https://www.engineai.com", "status": "pilot", "country": "China"},
    {"name": "EngineAI T800", "vendor": "EngineAI", "model_slug": "engineai-t800", "product_url": "https://www.engineai.com", "status": "research", "country": "China"},
    {"name": "Fourier GR-1", "vendor": "Fourier Intelligence", "model_slug": "fourier-gr1", "product_url": "https://www.fourierintelligence.com", "status": "pilot", "country": "China"},
    {"name": "Fourier GR-2", "vendor": "Fourier Intelligence", "model_slug": "fourier-gr2", "product_url": "https://www.fourierintelligence.com", "status": "pilot", "country": "China"},
    {"name": "XPeng PX5", "vendor": "XPeng Robotics", "model_slug": "xpeng-px5", "product_url": "https://www.xpeng.com", "status": "pilot", "country": "China"},
    {"name": "XPeng Iron", "vendor": "XPeng Robotics", "model_slug": "xpeng-iron", "product_url": "https://www.xpeng.com", "status": "research", "country": "China"},
    {"name": "Leju Kuavo", "vendor": "Leju Robotics", "model_slug": "leju-kuavo", "product_url": "https://www.lejurobotics.com", "status": "pilot", "country": "China"},
    {"name": "Neura 4NE1", "vendor": "Neura Robotics", "model_slug": "neura-4ne1", "product_url": "https://neura-robotics.com", "status": "pilot", "country": "Germany"},
    {"name": "PAL Robotics TALOS", "vendor": "PAL Robotics", "model_slug": "pal-talos", "product_url": "https://pal-robotics.com", "status": "research", "country": "Spain"},
    {"name": "PAL Robotics REEM-C", "vendor": "PAL Robotics", "model_slug": "pal-reem-c", "product_url": "https://pal-robotics.com", "status": "research", "country": "Spain"},
    {"name": "Engineered Arts Ameca", "vendor": "Engineered Arts", "model_slug": "engineered-arts-ameca", "product_url": "https://engineeredarts.com", "status": "available", "country": "UK"},
    {"name": "Reflex Humanoid", "vendor": "Reflex Robotics", "model_slug": "reflex-humanoid", "product_url": "https://reflexrobotics.com", "status": "pilot", "country": "USA"},
    {"name": "MenteeBot", "vendor": "Mentee Robotics", "model_slug": "mentee-bot", "product_url": "https://menteebotics.com", "status": "pilot", "country": "Israel"},
    {"name": "Persona AI Gen1", "vendor": "Persona AI", "model_slug": "persona-ai-gen1", "product_url": "https://persona.ai", "status": "pilot", "country": "USA"},
    {"name": "Xiaomi CyberOne", "vendor": "Xiaomi", "model_slug": "xiaomi-cyberone", "product_url": "https://www.mi.com", "status": "research", "country": "China"},
    {"name": "Toyota T-HR3", "vendor": "Toyota", "model_slug": "toyota-thr3", "product_url": "https://global.toyota", "status": "research", "country": "Japan"},
    {"name": "Honda ASIMO Successor", "vendor": "Honda", "model_slug": "honda-asimo-successor", "product_url": "https://global.honda", "status": "research", "country": "Japan"},
    {"name": "Rainbow HUBO", "vendor": "Rainbow Robotics", "model_slug": "rainbow-hubo", "product_url": "https://www.rainbow-robotics.com", "status": "research", "country": "South Korea"},
    {"name": "Preferred Networks Humanoid", "vendor": "Preferred Networks", "model_slug": "pfn-humanoid", "product_url": "https://preferred.jp", "status": "research", "country": "Japan"},
    # ── China startups & scale players ───────────────────────────────────────
    {"name": "Astribot S1", "vendor": "Astribot", "model_slug": "astribot-s1", "status": "pilot", "country": "China"},
    {"name": "Galbot G1", "vendor": "Galbot", "model_slug": "galbot-g1", "status": "pilot", "country": "China"},
    {"name": "Robotera STAR1", "vendor": "Robotera", "model_slug": "robotera-star1", "status": "pilot", "country": "China"},
    {"name": "LimX TRON1", "vendor": "LimX Dynamics", "model_slug": "limx-tron1", "status": "pilot", "country": "China"},
    {"name": "Kepler Forerunner K2", "vendor": "Kepler Exploration Robotics", "model_slug": "kepler-k2", "status": "pilot", "country": "China"},
    {"name": "Booster T1", "vendor": "Booster Robotics", "model_slug": "booster-t1", "status": "pilot", "country": "China"},
    {"name": "MagicLab Humanoid", "vendor": "MagicLab", "model_slug": "magiclab-humanoid", "status": "research", "country": "China"},
    {"name": "Spirit AI Humanoid", "vendor": "Spirit AI", "model_slug": "spirit-ai-humanoid", "status": "research", "country": "China"},
    {"name": "Stardust Intelligence", "vendor": "Stardust Intelligence", "model_slug": "stardust-humanoid", "status": "research", "country": "China"},
    {"name": "DroidUp Humanoid", "vendor": "DroidUp", "model_slug": "droidup-humanoid", "status": "research", "country": "China"},
    {"name": "Origin Dynamics Humanoid", "vendor": "Origin Dynamics", "model_slug": "origin-dynamics-humanoid", "status": "research", "country": "China"},
    {"name": "PNDbotics Adam", "vendor": "PNDbotics", "model_slug": "pndbotics-adam", "status": "pilot", "country": "China"},
    {"name": "Noetix N2", "vendor": "Noetix Robotics", "model_slug": "noetix-n2", "status": "pilot", "country": "China"},
    {"name": "OpenLoong Humanoid", "vendor": "OpenLoong", "model_slug": "openloong-humanoid", "status": "research", "country": "China"},
    {"name": "Qinglong Humanoid", "vendor": "Qinglong Bot", "model_slug": "qinglong-humanoid", "status": "research", "country": "China"},
    {"name": "Tianqing Robotics Humanoid", "vendor": "Tianqing Robotics", "model_slug": "tianqing-humanoid", "status": "research", "country": "China"},
    {"name": "Elephant Robotics Humanoid", "vendor": "Elephant Robotics", "model_slug": "elephant-humanoid", "status": "research", "country": "China"},
    {"name": "CloudMinds Ginger XR", "vendor": "CloudMinds", "model_slug": "cloudminds-ginger-xr", "status": "pilot", "country": "China"},
    {"name": "Siasun Humanoid", "vendor": "Siasun", "model_slug": "siasun-humanoid", "status": "research", "country": "China"},
    {"name": "Estun Codroid", "vendor": "Estun Automation", "model_slug": "estun-codroid", "status": "research", "country": "China"},
    {"name": "Deep Robotics DR01", "vendor": "Deep Robotics", "model_slug": "deep-robotics-dr01", "status": "research", "country": "China"},
    {"name": "Lanxin Technology Humanoid", "vendor": "Lanxin Technology", "model_slug": "lanxin-humanoid", "status": "research", "country": "China"},
    {"name": "Matrix Hyper Humanoid", "vendor": "Matrix Hyper", "model_slug": "matrix-hyper-humanoid", "status": "research", "country": "China"},
    {"name": "Realman Humanoid", "vendor": "Realman Robotics", "model_slug": "realman-humanoid", "status": "research", "country": "China"},
    {"name": "JAKA Humanoid", "vendor": "JAKA Robotics", "model_slug": "jaka-humanoid", "status": "research", "country": "China"},
    {"name": "Han's Humanoid", "vendor": "Han's Robot", "model_slug": "hans-humanoid", "status": "research", "country": "China"},
    {"name": "STEP Humanoid", "vendor": "STEP Robotics", "model_slug": "step-humanoid", "status": "research", "country": "China"},
    {"name": "Ti5 Humanoid", "vendor": "Ti5 Robot", "model_slug": "ti5-humanoid", "status": "research", "country": "China"},
    {"name": "Paxini Humanoid", "vendor": "Paxini Robotics", "model_slug": "paxini-humanoid", "status": "research", "country": "China"},
    {"name": "Rhino Robotics Humanoid", "vendor": "Rhino Robotics", "model_slug": "rhino-humanoid", "status": "research", "country": "China"},
    {"name": "Giant.AI Humanoid", "vendor": "Giant.AI", "model_slug": "giant-ai-humanoid", "status": "research", "country": "China"},
    {"name": "Humanoid Robot (HR)", "vendor": "Humanoid Robot Corp", "model_slug": "humanoid-robot-corp", "status": "research", "country": "China"},
    {"name": "Xiaomi CyberOne Pro", "vendor": "Xiaomi Robotics", "model_slug": "xiaomi-cyberone-pro", "status": "research", "country": "China"},
    {"name": "Chery Mornine", "vendor": "Chery Robotics", "model_slug": "chery-mornine", "status": "pilot", "country": "China"},
    {"name": "Haier Humanoid", "vendor": "Haier Robotics", "model_slug": "haier-humanoid", "status": "research", "country": "China"},
    {"name": "Geely Humanoid", "vendor": "Geely Robotics", "model_slug": "geely-humanoid", "status": "research", "country": "China"},
    {"name": "BYD Humanoid", "vendor": "BYD Robotics", "model_slug": "byd-humanoid", "status": "research", "country": "China"},
    {"name": "NIO Humanoid", "vendor": "NIO Robotics", "model_slug": "nio-humanoid", "status": "research", "country": "China"},
    {"name": "Li Auto Humanoid", "vendor": "Li Auto Robotics", "model_slug": "liauto-humanoid", "status": "research", "country": "China"},
    {"name": "ZTE Humanoid", "vendor": "ZTE Robotics", "model_slug": "zte-humanoid", "status": "research", "country": "China"},
    {"name": "Huawei Humanoid", "vendor": "Huawei Robotics", "model_slug": "huawei-humanoid", "status": "research", "country": "China"},
    {"name": "SenseTime Humanoid", "vendor": "SenseTime", "model_slug": "sensetime-humanoid", "status": "research", "country": "China"},
    {"name": "Megvii Humanoid", "vendor": "Megvii", "model_slug": "megvii-humanoid", "status": "research", "country": "China"},
    {"name": "Horizon Humanoid", "vendor": "Horizon Robotics", "model_slug": "horizon-humanoid", "status": "research", "country": "China"},
    {"name": "DJI Humanoid", "vendor": "DJI Robotics", "model_slug": "dji-humanoid", "status": "research", "country": "China"},
    {"name": "Dreame Humanoid", "vendor": "Dreame Robotics", "model_slug": "dreame-humanoid", "status": "research", "country": "China"},
    {"name": "Ecovacs Humanoid", "vendor": "Ecovacs Robotics", "model_slug": "ecovacs-humanoid", "status": "research", "country": "China"},
    {"name": "Roborock Humanoid", "vendor": "Roborock", "model_slug": "roborock-humanoid", "status": "research", "country": "China"},
    {"name": "Ninebot Humanoid", "vendor": "Ninebot Robotics", "model_slug": "ninebot-humanoid", "status": "research", "country": "China"},
    {"name": "Segway Humanoid", "vendor": "Segway Robotics", "model_slug": "segway-humanoid", "status": "research", "country": "China"},
    {"name": "CloudWalk Humanoid", "vendor": "CloudWalk", "model_slug": "cloudwalk-humanoid", "status": "research", "country": "China"},
    {"name": "Iflytek Humanoid", "vendor": "Iflytek Robotics", "model_slug": "iflytek-humanoid", "status": "research", "country": "China"},
    {"name": "Baidu Humanoid", "vendor": "Baidu Robotics", "model_slug": "baidu-humanoid", "status": "research", "country": "China"},
    {"name": "Alibaba Humanoid", "vendor": "Alibaba DAMO Academy", "model_slug": "alibaba-humanoid", "status": "research", "country": "China"},
    {"name": "Tencent Humanoid", "vendor": "Tencent Robotics", "model_slug": "tencent-humanoid", "status": "research", "country": "China"},
    {"name": "ByteDance Humanoid", "vendor": "ByteDance Robotics", "model_slug": "bytedance-humanoid", "status": "research", "country": "China"},
    {"name": "Meituan Humanoid", "vendor": "Meituan Robotics", "model_slug": "meituan-humanoid", "status": "research", "country": "China"},
    {"name": "JD Humanoid", "vendor": "JD Robotics", "model_slug": "jd-humanoid", "status": "research", "country": "China"},
    {"name": "SF Express Humanoid", "vendor": "SF Express Robotics", "model_slug": "sf-humanoid", "status": "research", "country": "China"},
    {"name": "Cainiao Humanoid", "vendor": "Cainiao Robotics", "model_slug": "cainiao-humanoid", "status": "research", "country": "China"},
    {"name": "Geek+ Humanoid", "vendor": "Geek+", "model_slug": "geekplus-humanoid", "status": "research", "country": "China"},
    {"name": "Hai Robotics Humanoid", "vendor": "Hai Robotics", "model_slug": "hai-humanoid", "status": "research", "country": "China"},
    {"name": "Quicktron Humanoid", "vendor": "Quicktron Robotics", "model_slug": "quicktron-humanoid", "status": "research", "country": "China"},
    {"name": "ForwardX Humanoid", "vendor": "ForwardX Robotics", "model_slug": "forwardx-humanoid", "status": "research", "country": "China"},
    {"name": "VisionNav Humanoid", "vendor": "VisionNav Robotics", "model_slug": "visionnav-humanoid", "status": "research", "country": "China"},
    {"name": "Syrius Humanoid", "vendor": "Syrius Robotics", "model_slug": "syrius-humanoid", "status": "research", "country": "China"},
    {"name": "Youibot Humanoid", "vendor": "Youibot", "model_slug": "youibot-humanoid", "status": "research", "country": "China"},
    {"name": "Standard Robots Humanoid", "vendor": "Standard Robots", "model_slug": "standard-robots-humanoid", "status": "research", "country": "China"},
    {"name": "Seer Humanoid", "vendor": "SEER Robotics", "model_slug": "seer-humanoid", "status": "research", "country": "China"},
    {"name": "HIT Robot Group Humanoid", "vendor": "HIT Robot Group", "model_slug": "hit-humanoid", "status": "research", "country": "China"},
    {"name": "Suzhou Pangolin Humanoid", "vendor": "Pangolin Robot", "model_slug": "pangolin-humanoid", "status": "research", "country": "China"},
    {"name": "Elephant Paxini Humanoid", "vendor": "Elephant Paxini", "model_slug": "elephant-paxini-humanoid", "status": "research", "country": "China"},
    {"name": "Clone Alpha", "vendor": "Clone Robotics", "model_slug": "clone-alpha", "status": "research", "country": "Poland"},
    {"name": "Halodi Eve", "vendor": "Halodi Robotics", "model_slug": "halodi-eve", "status": "research", "country": "Norway"},
    {"name": "Shadow Dexterous Hand Platform", "vendor": "Shadow Robot Company", "model_slug": "shadow-hand-platform", "status": "research", "country": "UK"},
    {"name": "IHMC Atlas Research", "vendor": "IHMC Robotics", "model_slug": "ihmc-atlas", "status": "research", "country": "USA"},
    {"name": "NASA Valkyrie", "vendor": "NASA Johnson", "model_slug": "nasa-valkyrie", "status": "research", "country": "USA"},
    {"name": "DLR TORO", "vendor": "DLR", "model_slug": "dlr-toro", "status": "research", "country": "Germany"},
    {"name": "DLR Rollin' Justin", "vendor": "DLR", "model_slug": "dlr-justin", "status": "research", "country": "Germany"},
    {"name": "Kawasaki Kaleido", "vendor": "Kawasaki Robotics", "model_slug": "kawasaki-kaleido", "status": "research", "country": "Japan"},
    {"name": "Honda Avatar", "vendor": "Honda R&D", "model_slug": "honda-avatar", "status": "research", "country": "Japan"},
    {"name": "SoftBank Pepper Next", "vendor": "SoftBank Robotics", "model_slug": "softbank-pepper-next", "status": "research", "country": "Japan"},
    {"name": "Toyota Punyo", "vendor": "Toyota Research", "model_slug": "toyota-punyo", "status": "research", "country": "Japan"},
    {"name": "Samsung Bot Handy", "vendor": "Samsung Research", "model_slug": "samsung-bot-handy", "status": "research", "country": "South Korea"},
    {"name": "LG CLOi SuitBot", "vendor": "LG Electronics", "model_slug": "lg-cloi-suitbot", "status": "research", "country": "South Korea"},
    {"name": "Hyundai Boston Dynamics Atlas", "vendor": "Hyundai Robotics", "model_slug": "hyundai-atlas", "status": "pilot", "country": "South Korea"},
    {"name": "Skydio Humanoid Research", "vendor": "Skydio Robotics Lab", "model_slug": "skydio-humanoid", "status": "research", "country": "USA"},
    {"name": "Amazon Digit Pilot", "vendor": "Amazon Robotics", "model_slug": "amazon-digit", "status": "pilot", "country": "USA"},
    {"name": "BMW Figure Pilot", "vendor": "BMW Manufacturing", "model_slug": "bmw-figure-pilot", "status": "pilot", "country": "Germany"},
    {"name": "Mercedes Apptronik Pilot", "vendor": "Mercedes-Benz", "model_slug": "mercedes-apptronik", "status": "pilot", "country": "Germany"},
    {"name": "BMW Apptronik Pilot", "vendor": "BMW Group", "model_slug": "bmw-apptronik", "status": "pilot", "country": "Germany"},
    {"name": "GXO Agility Digit", "vendor": "GXO Logistics", "model_slug": "gxo-digit", "status": "pilot", "country": "USA"},
    {"name": "Schaeffler Neura 4NE1", "vendor": "Schaeffler", "model_slug": "schaeffler-4ne1", "status": "pilot", "country": "Germany"},
    {"name": "Mercedes Figure Pilot", "vendor": "Mercedes-Benz Manufacturing", "model_slug": "mercedes-figure", "status": "pilot", "country": "Germany"},
    {"name": "BMW Figure Pilot", "vendor": "BMW Manufacturing", "model_slug": "bmw-figure", "status": "pilot", "country": "Germany"},
    {"name": "Foxconn Optimus Pilot", "vendor": "Foxconn", "model_slug": "foxconn-optimus", "status": "pilot", "country": "Taiwan"},
    {"name": "Foxconn Unitree Pilot", "vendor": "Foxconn", "model_slug": "foxconn-unitree", "status": "pilot", "country": "Taiwan"},
    {"name": "NVIDIA GR00T Partner Humanoid", "vendor": "NVIDIA Robotics", "model_slug": "nvidia-gr00t-humanoid", "status": "research", "country": "USA"},
    {"name": "Physical Intelligence Research", "vendor": "Physical Intelligence", "model_slug": "pi-humanoid-research", "status": "research", "country": "USA"},
    {"name": "Skild AI Foundation Model", "vendor": "Skild AI", "model_slug": "skild-humanoid-stack", "status": "research", "country": "USA"},
    {"name": "Covariant Humanoid Stack", "vendor": "Covariant", "model_slug": "covariant-humanoid", "status": "research", "country": "USA"},
    {"name": "OpenAI Humanoid Partner", "vendor": "OpenAI Robotics", "model_slug": "openai-humanoid-partner", "status": "research", "country": "USA"},
    {"name": "Meta FAIR Humanoid", "vendor": "Meta FAIR", "model_slug": "meta-fair-humanoid", "status": "research", "country": "USA"},
    {"name": "Google DeepMind Humanoid", "vendor": "Google DeepMind", "model_slug": "deepmind-humanoid", "status": "research", "country": "UK"},
    {"name": "Waymo Humanoid Research", "vendor": "Waymo", "model_slug": "waymo-humanoid", "status": "research", "country": "USA"},
    {"name": "Apple Robotics Humanoid", "vendor": "Apple Robotics", "model_slug": "apple-humanoid", "status": "research", "country": "USA"},
    {"name": "Microsoft Azure Humanoid", "vendor": "Microsoft Robotics", "model_slug": "microsoft-humanoid", "status": "research", "country": "USA"},
    {"name": "Intel Humanoid Lab", "vendor": "Intel Labs", "model_slug": "intel-humanoid", "status": "research", "country": "USA"},
    {"name": "Qualcomm Humanoid Platform", "vendor": "Qualcomm", "model_slug": "qualcomm-humanoid", "status": "research", "country": "USA"},
    {"name": "AMD Humanoid Platform", "vendor": "AMD", "model_slug": "amd-humanoid", "status": "research", "country": "USA"},
    {"name": "ARM Humanoid Platform", "vendor": "ARM Robotics", "model_slug": "arm-humanoid", "status": "research", "country": "UK"},
    {"name": "Siemens Humanoid Pilot", "vendor": "Siemens", "model_slug": "siemens-humanoid", "status": "research", "country": "Germany"},
    {"name": "ABB Humanoid Research", "vendor": "ABB Robotics", "model_slug": "abb-humanoid", "status": "research", "country": "Switzerland"},
    {"name": "Fanuc Humanoid Research", "vendor": "Fanuc", "model_slug": "fanuc-humanoid", "status": "research", "country": "Japan"},
    {"name": "KUKA Humanoid Research", "vendor": "KUKA", "model_slug": "kuka-humanoid", "status": "research", "country": "Germany"},
    {"name": "Yaskawa Humanoid Research", "vendor": "Yaskawa", "model_slug": "yaskawa-humanoid", "status": "research", "country": "Japan"},
    {"name": "Universal Robots Humanoid", "vendor": "Universal Robots", "model_slug": "ur-humanoid", "status": "research", "country": "Denmark"},
    {"name": "Techman Humanoid", "vendor": "Techman Robot", "model_slug": "techman-humanoid", "status": "research", "country": "Taiwan"},
    {"name": "Doosan Humanoid", "vendor": "Doosan Robotics", "model_slug": "doosan-humanoid", "status": "research", "country": "South Korea"},
    {"name": "Franka Humanoid", "vendor": "Franka Emika", "model_slug": "franka-humanoid", "status": "research", "country": "Germany"},
    {"name": "Comau Humanoid", "vendor": "Comau", "model_slug": "comau-humanoid", "status": "research", "country": "Italy"},
    {"name": "Epson Humanoid", "vendor": "Epson Robotics", "model_slug": "epson-humanoid", "status": "research", "country": "Japan"},
    {"name": "Omron Humanoid", "vendor": "Omron Robotics", "model_slug": "omron-humanoid", "status": "research", "country": "Japan"},
    {"name": "Mitsubishi Humanoid", "vendor": "Mitsubishi Electric", "model_slug": "mitsubishi-humanoid", "status": "research", "country": "Japan"},
    {"name": "Denso Humanoid", "vendor": "Denso Robotics", "model_slug": "denso-humanoid", "status": "research", "country": "Japan"},
    {"name": "Nidec Humanoid", "vendor": "Nidec Robotics", "model_slug": "nidec-humanoid", "status": "research", "country": "Japan"},
    {"name": "Harmonic Drive Humanoid", "vendor": "Harmonic Drive", "model_slug": "harmonic-humanoid", "status": "research", "country": "Japan"},
    {"name": "Maxon Humanoid Actuator Kit", "vendor": "Maxon Group", "model_slug": "maxon-humanoid-kit", "status": "research", "country": "Switzerland"},
    {"name": "Tesla Optimus Gen 1", "vendor": "Tesla", "model_slug": "tesla-optimus-gen1", "status": "research", "country": "USA"},
    {"name": "Sanctuary M-Series", "vendor": "Sanctuary AI", "model_slug": "sanctuary-m-series", "status": "research", "country": "Canada"},
    {"name": "Apptronik A2", "vendor": "Apptronik", "model_slug": "apptronik-a2", "status": "research", "country": "USA"},
    {"name": "Agility Digit 2", "vendor": "Agility Robotics", "model_slug": "agility-digit-2", "status": "pilot", "country": "USA"},
    {"name": "Figure 03", "vendor": "Figure AI", "model_slug": "figure-03", "status": "research", "country": "USA"},
    {"name": "1X NEO Beta", "vendor": "1X Technologies", "model_slug": "1x-neo-beta", "status": "pilot", "country": "USA"},
    {"name": "Zhiyuan Lingxi", "vendor": "Zhiyuan Robotics", "model_slug": "zhiyuan-lingxi", "status": "pilot", "country": "China"},
    {"name": "Leju Kuavo 3", "vendor": "Leju Robotics", "model_slug": "leju-kuavo-3", "status": "pilot", "country": "China"},
    {"name": "Astribot S2", "vendor": "Astribot", "model_slug": "astribot-s2", "status": "pilot", "country": "China"},
    {"name": "Galbot G2", "vendor": "Galbot", "model_slug": "galbot-g2", "status": "pilot", "country": "China"},
    {"name": "Robotera STAR2", "vendor": "Robotera", "model_slug": "robotera-star2", "status": "pilot", "country": "China"},
    {"name": "LimX Oli", "vendor": "LimX Dynamics", "model_slug": "limx-oli", "status": "pilot", "country": "China"},
    {"name": "Kepler Forerunner K1", "vendor": "Kepler Exploration Robotics", "model_slug": "kepler-k1", "status": "research", "country": "China"},
    {"name": "Booster K1", "vendor": "Booster Robotics", "model_slug": "booster-k1", "status": "research", "country": "China"},
    {"name": "PNDbotics Adam U", "vendor": "PNDbotics", "model_slug": "pndbotics-adam-u", "status": "pilot", "country": "China"},
    {"name": "Noetix E1", "vendor": "Noetix Robotics", "model_slug": "noetix-e1", "status": "research", "country": "China"},
    {"name": "EngineAI SA01", "vendor": "EngineAI", "model_slug": "engineai-sa01", "status": "research", "country": "China"},
    {"name": "Fourier N1", "vendor": "Fourier Intelligence", "model_slug": "fourier-n1", "status": "research", "country": "China"},
    {"name": "Neura MAiRA", "vendor": "Neura Robotics", "model_slug": "neura-maira", "status": "pilot", "country": "Germany"},
    {"name": "PAL Robotics ARI", "vendor": "PAL Robotics", "model_slug": "pal-ari", "status": "research", "country": "Spain"},
    {"name": "Engineered Arts Mesmer", "vendor": "Engineered Arts", "model_slug": "engineered-arts-mesmer", "status": "available", "country": "UK"},
    {"name": "Reflex Gen2", "vendor": "Reflex Robotics", "model_slug": "reflex-gen2", "status": "pilot", "country": "USA"},
    {"name": "MenteeBot Pro", "vendor": "Mentee Robotics", "model_slug": "mentee-bot-pro", "status": "pilot", "country": "Israel"},
    {"name": "Persona AI Gen2", "vendor": "Persona AI", "model_slug": "persona-ai-gen2", "status": "pilot", "country": "USA"},
]


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return s[:80] or "humanoid"


def normalize_catalog_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure model_slug and default fields exist."""
    out = dict(entry)
    if not out.get("model_slug"):
        out["model_slug"] = slugify(f"{out.get('vendor', '')}-{out.get('name', '')}")
    out.setdefault("status", "research")
    out.setdefault("specs", {})
    out.setdefault("product_url", None)
    out.setdefault("country", None)
    return out


def catalog_entries() -> List[Dict[str, Any]]:
    return [normalize_catalog_entry(e) for e in HUMANOID_CATALOG]


def catalog_count() -> int:
    return len(HUMANOID_CATALOG)
