export interface BuyerQuote {
  id: string;
  author: string;
  title: string;
  company: string;
  industry: string;
  avatarUrl?: string;
  quote: string;
  targetRobotTypes: string[];
  timeline: string;
  verified: boolean;
  date: string;
  matchedJobTitle: string;
  opportunityHref: string;
  location: string;
  heatTier: "HOT" | "WARM" | "HIGH MATCH";
}

export const FEATURED_BUYER_QUOTES: BuyerQuote[] = [
  {
    id: "quote-cloudkitchens",
    author: "Justin Futterman",
    title: "Director of Operations",
    company: "CloudKitchens",
    industry: "Ghost Kitchens & QSR",
    quote:
      "Scaling order fulfillment across our kitchen network requires automated meal portioning and prep cobots that can handle peak rush volumes without constant human intervention.",
    targetRobotTypes: ["Meal Assembly Cobots", "Kitchen Prep Manipulators"],
    timeline: "Active Evaluation",
    verified: true,
    date: "Today",
    matchedJobTitle: "Kitchen Meal Assembly Cobot Operator",
    opportunityHref: "/pipeline?co=CloudKitchens&q=CloudKitchens",
    location: "Austin, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-fedex",
    author: "David Perillat",
    title: "Regional Operations Director",
    company: "FedEx Ground",
    industry: "Logistics & Surface Freight",
    quote:
      "Peak season package volumes and heavy pallet staging in regional hubs demand autonomous forklifts and sortation AMRs that integrate directly into our dock workflows.",
    targetRobotTypes: ["Autonomous Forklifts", "Parcel Sortation AMRs"],
    timeline: "Immediate Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Hub Parcel Sortation & Heavy Pallet AMR Operator",
    opportunityHref: "/pipeline?co=FedEx&q=FedEx",
    location: "Memphis, TN",
    heatTier: "HOT",
  },
  {
    id: "quote-ryder",
    author: "Neal Medeiros",
    title: "Director of Customer Logistics",
    company: "Ryder System",
    industry: "3PL & Warehousing",
    quote:
      "Dock-to-stock cycle times are our primary KPI. We are actively evaluating heavy-payload AMRs and case-picking cobots for dedicated fulfillment centers across North America.",
    targetRobotTypes: ["Heavy Pallet AMRs", "Case-Picking Cobots"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Dock-to-Stock Heavy Pallet AMR Specialist",
    opportunityHref: "/pipeline?co=Ryder&q=Ryder",
    location: "Dallas, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-lineage",
    author: "Marcus Vance",
    title: "VP of Automation Engineering",
    company: "Lineage Logistics",
    industry: "Cold Storage & 3PL Logistics",
    quote:
      "Sub-zero cold storage labor turnover is a continuous operational challenge. Replacing manual shuttle runs with sub-zero rated AMRs increases throughput and protects personnel.",
    targetRobotTypes: ["Cold-Storage Heavy AMRs", "Pallet Shuttle Robots"],
    timeline: "Immediate Deployment",
    verified: true,
    date: "Today",
    matchedJobTitle: "Cold-Storage Sub-Zero Pallet AMR Lead",
    opportunityHref: "/pipeline?co=Lineage&q=Lineage",
    location: "Chicago, IL",
    heatTier: "HOT",
  },
  {
    id: "quote-hyatt",
    author: "Sarah Jenkins",
    title: "Director of Guest Services & Operations",
    company: "Hyatt Hotels",
    industry: "Hospitality & Commercial Facilities",
    quote:
      "Housekeeping staffing pressure across properties led us to automate floor maintenance and hallway transport so our team focuses 100% on guest satisfaction.",
    targetRobotTypes: ["Commercial Cleaning AMRs", "Service Busing Robots"],
    timeline: "Active Evaluation",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Hospitality Floor Scrubber & Service AMR",
    opportunityHref: "/pipeline?co=Hyatt&q=Hyatt",
    location: "Atlanta, GA",
    heatTier: "HOT",
  },
  {
    id: "quote-chipotle",
    author: "Michael Thoms",
    title: "Vice President of Operations",
    company: "Chipotle",
    industry: "Fast Casual & Food Prep",
    quote:
      "Kitchen prep labor bottlenecks are where we see immediate automation ROI. We're evaluating produce prep manipulators and portioning units to increase store kitchen throughput.",
    targetRobotTypes: [
      "Produce Prep Manipulators",
      "Automated Portioning Units",
    ],
    timeline: "3–6 Months Pilot",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Produce Prep & Automated Portioning Unit",
    opportunityHref: "/pipeline?co=Chipotle&q=Chipotle",
    location: "Columbus, OH",
    heatTier: "WARM",
  },
  {
    id: "quote-abm",
    author: "Ralph Sica",
    title: "Vice President of Operations",
    company: "ABM Industries",
    industry: "Facility Services & Janitorial",
    quote:
      "Commercial janitorial staffing deficits across airport terminals and large enterprise facilities make autonomous floor scrubbers essential for maintaining off-peak cleaning compliance.",
    targetRobotTypes: ["Commercial Cleaning AMRs", "Vacuuming Cobots"],
    timeline: "Active Evaluation",
    verified: true,
    date: "3 days ago",
    matchedJobTitle: "Commercial Janitorial & Terminal Scrubber AMR",
    opportunityHref: "/pipeline?co=ABM&q=ABM",
    location: "New York, NY",
    heatTier: "HOT",
  },
  {
    id: "quote-thompson",
    author: "Zandrique Harrold",
    title: "Vice President of Operations",
    company: "Thompson Hospitality",
    industry: "Hospitality & Corporate Dining",
    quote:
      "High labor turnover in corporate dining halls is driving us to automate tray busing and floor maintenance so our staff can focus 100% on hospitality and guest service.",
    targetRobotTypes: ["Tray Delivery Cobots", "Service AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Dining Hall Tray Busing & Service AMR",
    opportunityHref: "/pipeline?co=Thompson&q=Thompson",
    location: "Reston, VA",
    heatTier: "WARM",
  },
  {
    id: "quote-wonder",
    author: "Deniz Uzel",
    title: "Vice President of Operations",
    company: "Wonder Group",
    industry: "Multi-Brand Food Delivery",
    quote:
      "Scaling multi-brand meal assembly across suburban hub kitchens requires high-precision mobile manipulators that can switch between diverse menu SKUs smoothly.",
    targetRobotTypes: [
      "Multi-Step Assembly AMRs",
      "Automated Cooking Stations",
    ],
    timeline: "0–3 Months",
    verified: true,
    date: "3 days ago",
    matchedJobTitle: "Multi-Brand Meal Assembly Manipulator",
    opportunityHref: "/pipeline?co=Wonder&q=Wonder",
    location: "New York, NY",
    heatTier: "HOT",
  },
  {
    id: "quote-walmart",
    author: "Greg Henderson",
    title: "Director of Fulfillment Automation",
    company: "Walmart Supply Chain",
    industry: "E-Commerce & Retail Distribution",
    quote:
      "High-bay palletizing and automated tote consolidation in regional fulfillment centers are active CapEx priority projects with rapid vendor evaluation windows.",
    targetRobotTypes: [
      "High-Bay Palletizing Cobots",
      "Tote Consolidation AMRs",
    ],
    timeline: "Active Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "E-Commerce Fulfillment Palletizing Cobot",
    opportunityHref: "/pipeline?co=Walmart&q=Walmart",
    location: "Bentonville, AR",
    heatTier: "HOT",
  },
  {
    id: "quote-mayo",
    author: "Dr. Aris Thorne",
    title: "Director of Health System Logistics",
    company: "Mayo Clinic",
    industry: "Healthcare & Hospital Logistics",
    quote:
      "Internal specimen, linen, and pharmacy transport consumes hundreds of staff hours daily. Autonomous mobile cart units directly return valuable time to patient care.",
    targetRobotTypes: ["Hospital Transport AMRs", "Specimen Delivery Carts"],
    timeline: "0–3 Months Pilot",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Hospital Autonomous Specimen & Cart AMR",
    opportunityHref: "/pipeline?co=Mayo&q=Mayo",
    location: "Rochester, MN",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-boeing",
    author: "Elena Rostova",
    title: "Quality & Assembly Operations Director",
    company: "Boeing Commercial",
    industry: "Aerospace Manufacturing",
    quote:
      "Visual quality inspection mandates and heavy component positioning require high-precision mobile manipulators with verifiable digital audit trails.",
    targetRobotTypes: ["Inspection Manipulators", "Precision Component AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Aerospace Visual Inspection & Quality AMR",
    opportunityHref: "/pipeline?co=Boeing&q=Boeing",
    location: "Charleston, SC",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-kroger",
    author: "Brian O'Connor",
    title: "Senior Director of Micro-Fulfillment",
    company: "Kroger Fulfillment",
    industry: "Grocery & E-Commerce",
    quote:
      "Micro-fulfillment store hubs need fast case-handling cobots to reliably achieve 30-minute e-grocery pickup preparation commitments.",
    targetRobotTypes: ["Case Handling Cobots", "Order Picking AMRs"],
    timeline: "Immediate Evaluation",
    verified: true,
    date: "Today",
    matchedJobTitle: "E-Grocery Case Handling & Picking Cobot",
    opportunityHref: "/pipeline?co=Kroger&q=Kroger",
    location: "Cincinnati, OH",
    heatTier: "HOT",
  },
  {
    id: "quote-sysco",
    author: "Derek Vance",
    title: "VP of Fleet & Warehouse Automation",
    company: "Sysco Logistics",
    industry: "Foodservice Distribution & 3PL",
    quote:
      "Night-shift pallet staging labor shortages require heavy autonomous pallet jacks for continuous dock-to-staging operations without operational bottlenecks.",
    targetRobotTypes: ["Autonomous Pallet Jacks", "Dock Staging AMRs"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Night-Shift Dock-to-Staging Pallet Jack AMR",
    opportunityHref: "/pipeline?co=Sysco&q=Sysco",
    location: "Houston, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-tyson",
    author: "Carlos Mendez",
    title: "Plant Automation Lead",
    company: "Tyson Foods",
    industry: "Food Processing & Manufacturing",
    quote:
      "Primary packaging and box palletizing line bottlenecks require IP69K washdown-rated cobots capable of 24/7 continuous operation in food processing plants.",
    targetRobotTypes: ["IP69K Washdown Cobots", "Case Palletizers"],
    timeline: "Active Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Food Processing Line Washdown Palletizing Cobot",
    opportunityHref: "/pipeline?co=Tyson&q=Tyson",
    location: "Springdale, AR",
    heatTier: "HOT",
  },
  {
    id: "quote-target",
    author: "Amanda Sterling",
    title: "Director of Distribution Automation",
    company: "Target Supply Chain",
    industry: "Retail & E-Commerce Fulfillment",
    quote:
      "Sorting mixed-sku cartons onto outbound pallets at our regional fulfillment hubs requires vision-guided cobots and autonomous tuggers.",
    targetRobotTypes: [
      "Mixed-SKU Palletizing Cobots",
      "Autonomous Tow Tractors",
    ],
    timeline: "Immediate Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Outbound Mixed-SKU Palletizing Cobot Lead",
    opportunityHref: "/pipeline?co=Target&q=Target",
    location: "Minneapolis, MN",
    heatTier: "HOT",
  },
  {
    id: "quote-pg",
    author: "Kevin Zhang",
    title: "Global Packaging Automation Lead",
    company: "Procter & Gamble",
    industry: "Consumer Goods Manufacturing",
    quote:
      "End-of-line case packing and automated shrink wrapping lines need high-speed collaborative arms to eliminate ergonomic strain during peak production.",
    targetRobotTypes: ["Case Packing Cobots", "High-Speed Articulated Arms"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "End-of-Line High-Speed Case Packing Cobot",
    opportunityHref: "/pipeline?co=Procter&q=Procter",
    location: "Cincinnati, OH",
    heatTier: "HOT",
  },
  {
    id: "quote-dhl",
    author: "Jan-Willem van den Berg",
    title: "VP of Innovation & Robotics",
    company: "DHL Supply Chain",
    industry: "3PL & Freight Forwarding",
    quote:
      "Deploying mobile sortation robots across our multi-tenant logistics centers has reduced order processing lag by 40% during flash sale spikes.",
    targetRobotTypes: [
      "Parcel Sortation AMRs",
      "Goods-to-Person Mobile Robots",
    ],
    timeline: "Active Evaluation",
    verified: true,
    date: "Today",
    matchedJobTitle: "Multi-Tenant Parcel Sortation AMR Specialist",
    opportunityHref: "/pipeline?co=DHL&q=DHL",
    location: "Westerville, OH",
    heatTier: "HOT",
  },
  {
    id: "quote-tesla",
    author: "Stefan Lindner",
    title: "Senior Manager of Advanced Automation",
    company: "Tesla Gigafactory",
    industry: "Automotive & Battery Production",
    quote:
      "Heavy battery module positioning and sub-assembly transport between cell lines require 500kg+ payload AMRs with sub-millimeter dock alignment.",
    targetRobotTypes: [
      "Heavy-Payload Battery AMRs",
      "Precision Mobile Manipulators",
    ],
    timeline: "Immediate RFP",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Gigafactory Heavy Battery Module Transport AMR",
    opportunityHref: "/pipeline?co=Tesla&q=Tesla",
    location: "Austin, TX",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-cardinal",
    author: "Rachel Vance",
    title: "VP of Medical Distribution Operations",
    company: "Cardinal Health",
    industry: "Pharma & Healthcare Logistics",
    quote:
      "Sterile pharmaceutical tote transport and automated order consolidation require cleanroom-rated AMRs with audit-compliant lot tracking.",
    targetRobotTypes: ["Cleanroom Tote AMRs", "Pharma Consolidation Robots"],
    timeline: "0–3 Months",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Pharmaceutical Cleanroom Tote Transport AMR",
    opportunityHref: "/pipeline?co=Cardinal&q=Cardinal",
    location: "Dublin, OH",
    heatTier: "HOT",
  },
  {
    id: "quote-marriott",
    author: "Victor Rossi",
    title: "VP of Global Hotel Operations",
    company: "Marriott International",
    industry: "Hospitality & Resort Management",
    quote:
      "Automating commercial floor care across resort convention spaces frees our housekeeping specialists to deliver personalized guest experiences.",
    targetRobotTypes: ["Commercial Floor Scrubbers", "Linen Transport AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "Today",
    matchedJobTitle: "Convention Center Floor Care & Scrubber AMR",
    opportunityHref: "/pipeline?co=Marriott&q=Marriott",
    location: "Bethesda, MD",
    heatTier: "HOT",
  },
  {
    id: "quote-generalmills",
    author: "Sanjay Patel",
    title: "Manufacturing Technology Director",
    company: "General Mills",
    industry: "Food & Beverage Production",
    quote:
      "High-speed cereal box casing and pallet wrapping require IP65-rated cobots capable of multi-shift continuous duty without thermal throttling.",
    targetRobotTypes: [
      "Food-Grade Packaging Cobots",
      "Pallet Wrapping Manipulators",
    ],
    timeline: "Active Evaluation",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Food Processing Line High-Speed Casing Cobot",
    opportunityHref: "/pipeline?co=General+Mills&q=General+Mills",
    location: "Minneapolis, MN",
    heatTier: "WARM",
  },
  {
    id: "quote-cat",
    author: "Harlan Cooper",
    title: "Heavy Equipment Assembly Director",
    company: "Caterpillar Inc.",
    industry: "Heavy Machinery & Industrial Equipment",
    quote:
      "Welding cell feeding and heavy casting positioning require high-torque cobot arms and ruggedized AMR tuggers built for harsh foundry environments.",
    targetRobotTypes: ["Heavy Component Cobots", "Ruggedized AMR Tuggers"],
    timeline: "0–6 Months",
    verified: true,
    date: "3 days ago",
    matchedJobTitle: "Heavy Machinery Welding Cell & Casting Cobot",
    opportunityHref: "/pipeline?co=Caterpillar&q=Caterpillar",
    location: "Peoria, IL",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-deere",
    author: "Teresa Broek",
    title: "Director of Smart Manufacturing",
    company: "John Deere",
    industry: "Agricultural Equipment Manufacturing",
    quote:
      "Autonomous chassis painting and cab sub-assembly transport are central CapEx initiatives as we expand our smart manufacturing facilities.",
    targetRobotTypes: [
      "Chassis Painting Robots",
      "Sub-Assembly Transport AMRs",
    ],
    timeline: "Active Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Ag Equipment Chassis Sub-Assembly AMR Lead",
    opportunityHref: "/pipeline?co=John+Deere&q=John+Deere",
    location: "Moline, IL",
    heatTier: "HOT",
  },
  {
    id: "quote-prologis",
    author: "Elliot Vance",
    title: "Head of Logistics Park Innovation",
    company: "Prologis Essentials",
    industry: "Industrial Real Estate & Warehouse Infrastructure",
    quote:
      "Equipping our turnkey logistics parks with standardized AMR charging stations and fleet management nodes accelerates tenant automation onboarding.",
    targetRobotTypes: ["Fleet Docking Infrastructure", "Facility Patrol AMRs"],
    timeline: "Immediate Procurement",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Logistics Park AMR Fleet & Infrastructure Specialist",
    opportunityHref: "/pipeline?co=Prologis&q=Prologis",
    location: "San Francisco, CA",
    heatTier: "HOT",
  },
  {
    id: "quote-siemens",
    author: "Dr. Clara Weiss",
    title: "Head of Quality & Precision Manufacturing",
    company: "Siemens Healthineers",
    industry: "Medical Devices & Diagnostic Imaging",
    quote:
      "Automated optical inspection and sub-millimeter component placement cobots ensure zero-defect assembly for diagnostic imaging sensors.",
    targetRobotTypes: [
      "Optical Inspection Cobots",
      "Precision Assembly Manipulators",
    ],
    timeline: "0–3 Months Pilot",
    verified: true,
    date: "Today",
    matchedJobTitle: "Medical Device Precision Optical Inspection Cobot",
    opportunityHref: "/pipeline?co=Siemens&q=Siemens",
    location: "Malvern, PA",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-ups",
    author: "Marcus Thorne",
    title: "Director of Network Operations & Automation",
    company: "UPS Supply Chain",
    industry: "Express Package & Freight Logistics",
    quote:
      "Dock unload automation and irregular parcel sortation AMRs are critical to meeting next-day delivery commitments across air-hub gateways.",
    targetRobotTypes: ["Unload Assist Robots", "Irregular Freight AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Air-Hub Gateway Package Unload & Sortation AMR",
    opportunityHref: "/pipeline?co=UPS&q=UPS",
    location: "Louisville, KY",
    heatTier: "HOT",
  },
  {
    id: "quote-pepsico",
    author: "Julian Morales",
    title: "VP of Supply Chain Engineering",
    company: "PepsiCo Beverages",
    industry: "Beverage Bottling & Distribution",
    quote:
      "Heavy beverage case palletizing and autonomous yard shuttling keep our bottling plants running at 98%+ operational efficiency during summer peak.",
    targetRobotTypes: ["Beverage Case Palletizers", "Autonomous Yard Shuttles"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Today",
    matchedJobTitle: "Beverage Bottling Plant Case Palletizing Cobot",
    opportunityHref: "/pipeline?co=PepsiCo&q=PepsiCo",
    location: "Plano, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-geodis",
    author: "Lucia Moreau",
    title: "Director of Contract Logistics",
    company: "Geodis Logistics",
    industry: "Global 3PL & Warehousing",
    quote:
      "Automating piece-picking and bin replenishment across our omni-channel centers has eliminated inventory accuracy errors and reduced labor overtime.",
    targetRobotTypes: ["Piece-Picking Cobots", "Bin Replenishment AMRs"],
    timeline: "Active Evaluation",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Omni-Channel Piece-Picking & Bin Replenishment Cobot",
    opportunityHref: "/pipeline?co=Geodis&q=Geodis",
    location: "Brentwood, TN",
    heatTier: "HOT",
  },
  {
    id: "quote-abbott",
    author: "Nathaniel Cross",
    title: "Director of Device Manufacturing",
    company: "Abbott Laboratories",
    industry: "Pharmaceuticals & Diagnostic Kits",
    quote:
      "Rapid diagnostic kit packaging and tray loading require cleanroom-certified collaborative robot arms operating at 60+ units per minute.",
    targetRobotTypes: ["Cleanroom Packaging Cobots", "Diagnostic Tray Loaders"],
    timeline: "0–3 Months",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Diagnostic Kit Packaging & Cleanroom Tray Cobot",
    opportunityHref: "/pipeline?co=Abbott&q=Abbott",
    location: "Abbott Park, IL",
    heatTier: "HIGH MATCH",
  },
];
