export interface BuyerQuote {
  id: string;
  author: string;
  title: string;
  company: string;
  industry: string;
  avatarUrl?: string;
  quote: string;
  targetRobotTypes: string[];
  timeline: string;
  verified: boolean;
  date: string;
  matchedJobTitle: string;
  opportunityHref: string;
  location: string;
  heatTier: "HOT" | "WARM" | "HIGH MATCH";
}

export const FEATURED_BUYER_QUOTES: BuyerQuote[] = [
  {
    id: "quote-cloudkitchens",
    author: "Justin Futterman",
    title: "Director of Operations",
    company: "CloudKitchens",
    industry: "Ghost Kitchens & QSR",
    quote:
      "Scaling order fulfillment across our kitchen network requires automated meal portioning and prep cobots that can handle peak rush volumes without constant human intervention.",
    targetRobotTypes: ["Meal Assembly Cobots", "Kitchen Prep Manipulators"],
    timeline: "Active Evaluation",
    verified: true,
    date: "Today",
    matchedJobTitle: "Kitchen Meal Assembly Cobot Operator",
    opportunityHref: "/pipeline?co=CloudKitchens",
    location: "Austin, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-fedex",
    author: "David Perillat",
    title: "Regional Operations Director",
    company: "FedEx Ground",
    industry: "Logistics & Surface Freight",
    quote:
      "Peak season package volumes and heavy pallet staging in regional hubs demand autonomous forklifts and sortation AMRs that integrate directly into our dock workflows.",
    targetRobotTypes: ["Autonomous Forklifts", "Parcel Sortation AMRs"],
    timeline: "Immediate Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Hub Parcel Sortation & Heavy Pallet AMR Operator",
    opportunityHref: "/pipeline?co=FedEx",
    location: "Memphis, TN",
    heatTier: "HOT",
  },
  {
    id: "quote-ryder",
    author: "Neal Medeiros",
    title: "Director of Customer Logistics",
    company: "Ryder System",
    industry: "3PL & Warehousing",
    quote:
      "Dock-to-stock cycle times are our primary KPI. We are actively evaluating heavy-payload AMRs and case-picking cobots for dedicated fulfillment centers across North America.",
    targetRobotTypes: ["Heavy Pallet AMRs", "Case-Picking Cobots"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Dock-to-Stock Heavy Pallet AMR Specialist",
    opportunityHref: "/pipeline?co=Ryder",
    location: "Dallas, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-lineage",
    author: "Marcus Vance",
    title: "VP of Automation Engineering",
    company: "Lineage Logistics",
    industry: "Cold Storage & 3PL Logistics",
    quote:
      "Sub-zero cold storage labor turnover is a continuous operational challenge. Replacing manual shuttle runs with sub-zero rated AMRs increases throughput and protects personnel.",
    targetRobotTypes: ["Cold-Storage Heavy AMRs", "Pallet Shuttle Robots"],
    timeline: "Immediate Deployment",
    verified: true,
    date: "Today",
    matchedJobTitle: "Cold-Storage Sub-Zero Pallet AMR Lead",
    opportunityHref: "/pipeline?co=Lineage",
    location: "Chicago, IL",
    heatTier: "HOT",
  },
  {
    id: "quote-hyatt",
    author: "Sarah Jenkins",
    title: "Director of Guest Services & Operations",
    company: "Hyatt Hotels",
    industry: "Hospitality & Commercial Facilities",
    quote:
      "Housekeeping staffing pressure across properties led us to automate floor maintenance and hallway transport so our team focuses 100% on guest satisfaction.",
    targetRobotTypes: ["Commercial Cleaning AMRs", "Service Busing Robots"],
    timeline: "Active Evaluation",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Hospitality Floor Scrubber & Service AMR",
    opportunityHref: "/pipeline?co=Hyatt",
    location: "Atlanta, GA",
    heatTier: "HOT",
  },
  {
    id: "quote-chipotle",
    author: "Michael Thoms",
    title: "Vice President of Operations",
    company: "Chipotle",
    industry: "Fast Casual & Food Prep",
    quote:
      "Kitchen prep labor bottlenecks are where we see immediate automation ROI. We're evaluating produce prep manipulators and portioning units to increase store kitchen throughput.",
    targetRobotTypes: ["Produce Prep Manipulators", "Automated Portioning Units"],
    timeline: "3–6 Months Pilot",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Produce Prep & Automated Portioning Unit",
    opportunityHref: "/pipeline?co=Chipotle",
    location: "Columbus, OH",
    heatTier: "WARM",
  },
  {
    id: "quote-abm",
    author: "Ralph Sica",
    title: "Vice President of Operations",
    company: "ABM Industries",
    industry: "Facility Services & Janitorial",
    quote:
      "Commercial janitorial staffing deficits across airport terminals and large enterprise facilities make autonomous floor scrubbers essential for maintaining off-peak cleaning compliance.",
    targetRobotTypes: ["Commercial Cleaning AMRs", "Vacuuming Cobots"],
    timeline: "Active Evaluation",
    verified: true,
    date: "3 days ago",
    matchedJobTitle: "Commercial Janitorial & Terminal Scrubber AMR",
    opportunityHref: "/pipeline?co=ABM",
    location: "New York, NY",
    heatTier: "HOT",
  },
  {
    id: "quote-thompson",
    author: "Zandrique Harrold",
    title: "Vice President of Operations",
    company: "Thompson Hospitality",
    industry: "Hospitality & Corporate Dining",
    quote:
      "High labor turnover in corporate dining halls is driving us to automate tray busing and floor maintenance so our staff can focus 100% on hospitality and guest service.",
    targetRobotTypes: ["Tray Delivery Cobots", "Service AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Dining Hall Tray Busing & Service AMR",
    opportunityHref: "/pipeline?co=Thompson",
    location: "Reston, VA",
    heatTier: "WARM",
  },
  {
    id: "quote-wonder",
    author: "Deniz Uzel",
    title: "Vice President of Operations",
    company: "Wonder Group",
    industry: "Multi-Brand Food Delivery",
    quote:
      "Scaling multi-brand meal assembly across suburban hub kitchens requires high-precision mobile manipulators that can switch between diverse menu SKUs smoothly.",
    targetRobotTypes: ["Multi-Step Assembly AMRs", "Automated Cooking Stations"],
    timeline: "0–3 Months",
    verified: true,
    date: "3 days ago",
    matchedJobTitle: "Multi-Brand Meal Assembly Manipulator",
    opportunityHref: "/pipeline?co=Wonder",
    location: "New York, NY",
    heatTier: "HOT",
  },
  {
    id: "quote-walmart",
    author: "Greg Henderson",
    title: "Director of Fulfillment Automation",
    company: "Walmart Supply Chain",
    industry: "E-Commerce & Retail Distribution",
    quote:
      "High-bay palletizing and automated tote consolidation in regional fulfillment centers are active CapEx priority projects with rapid vendor evaluation windows.",
    targetRobotTypes: ["High-Bay Palletizing Cobots", "Tote Consolidation AMRs"],
    timeline: "Active Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "E-Commerce Fulfillment Palletizing Cobot",
    opportunityHref: "/pipeline?co=Walmart",
    location: "Bentonville, AR",
    heatTier: "HOT",
  },
  {
    id: "quote-mayo",
    author: "Dr. Aris Thorne",
    title: "Director of Health System Logistics",
    company: "Mayo Clinic",
    industry: "Healthcare & Hospital Logistics",
    quote:
      "Internal specimen, linen, and pharmacy transport consumes hundreds of staff hours daily. Autonomous mobile cart units directly return valuable time to patient care.",
    targetRobotTypes: ["Hospital Transport AMRs", "Specimen Delivery Carts"],
    timeline: "0–3 Months Pilot",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Hospital Autonomous Specimen & Cart AMR",
    opportunityHref: "/pipeline?co=Mayo",
    location: "Rochester, MN",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-boeing",
    author: "Elena Rostova",
    title: "Quality & Assembly Operations Director",
    company: "Boeing Commercial",
    industry: "Aerospace Manufacturing",
    quote:
      "Visual quality inspection mandates and heavy component positioning require high-precision mobile manipulators with verifiable digital audit trails.",
    targetRobotTypes: ["Inspection Manipulators", "Precision Component AMRs"],
    timeline: "Active RFP",
    verified: true,
    date: "2 days ago",
    matchedJobTitle: "Aerospace Visual Inspection & Quality AMR",
    opportunityHref: "/pipeline?co=Boeing",
    location: "Charleston, SC",
    heatTier: "HIGH MATCH",
  },
  {
    id: "quote-kroger",
    author: "Brian O'Connor",
    title: "Senior Director of Micro-Fulfillment",
    company: "Kroger Fulfillment",
    industry: "Grocery & E-Commerce",
    quote:
      "Micro-fulfillment store hubs need fast case-handling cobots to reliably achieve 30-minute e-grocery pickup preparation commitments.",
    targetRobotTypes: ["Case Handling Cobots", "Order Picking AMRs"],
    timeline: "Immediate Evaluation",
    verified: true,
    date: "Today",
    matchedJobTitle: "E-Grocery Case Handling & Picking Cobot",
    opportunityHref: "/pipeline?co=Kroger",
    location: "Cincinnati, OH",
    heatTier: "HOT",
  },
  {
    id: "quote-sysco",
    author: "Derek Vance",
    title: "VP of Fleet & Warehouse Automation",
    company: "Sysco Logistics",
    industry: "Foodservice Distribution & 3PL",
    quote:
      "Night-shift pallet staging labor shortages require heavy autonomous pallet jacks for continuous dock-to-staging operations without operational bottlenecks.",
    targetRobotTypes: ["Autonomous Pallet Jacks", "Dock Staging AMRs"],
    timeline: "0–3 Months Deployment",
    verified: true,
    date: "Yesterday",
    matchedJobTitle: "Night-Shift Dock-to-Staging Pallet Jack AMR",
    opportunityHref: "/pipeline?co=Sysco",
    location: "Houston, TX",
    heatTier: "HOT",
  },
  {
    id: "quote-tyson",
    author: "Carlos Mendez",
    title: "Plant Automation Lead",
    company: "Tyson Foods",
    industry: "Food Processing & Manufacturing",
    quote:
      "Primary packaging and box palletizing line bottlenecks require IP69K washdown-rated cobots capable of 24/7 continuous operation in food processing plants.",
    targetRobotTypes: ["IP69K Washdown Cobots", "Case Palletizers"],
    timeline: "Active Procurement",
    verified: true,
    date: "Today",
    matchedJobTitle: "Food Processing Line Washdown Palletizing Cobot",
    opportunityHref: "/pipeline?co=Tyson",
    location: "Springdale, AR",
    heatTier: "HOT",
  },
];
