"""Add robot_companies table for lead generation

Revision ID: 62c6bf204268
Revises: 
Create Date: 2026-03-07 04:39:24.389670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c6bf204268'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sub_industry', sa.String(), nullable=True),
    sa.Column('employee_estimate', sa.Integer(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('robot_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('headquarters_city', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('robot_type', sa.String(), nullable=True),
    sa.Column('target_market', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('us_presence', sa.String(), nullable=True),
    sa.Column('us_office_location', sa.String(), nullable=True),
    sa.Column('distributor_needed', sa.String(), nullable=True),
    sa.Column('distributor_urgency', sa.String(), nullable=True),
    sa.Column('system_integrator_network', sa.JSON(), nullable=True),
    sa.Column('has_us_partnerships', sa.Boolean(), nullable=True),
    sa.Column('partnership_stage', sa.String(), nullable=True),
    sa.Column('market_entry_wave', sa.String(), nullable=True),
    sa.Column('entry_priority', sa.String(), nullable=True),
    sa.Column('trade_shows', sa.JSON(), nullable=True),
    sa.Column('last_trade_show', sa.String(), nullable=True),
    sa.Column('next_trade_show', sa.String(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('funding_amount', sa.String(), nullable=True),
    sa.Column('investors', sa.JSON(), nullable=True),
    sa.Column('is_publicly_traded', sa.Boolean(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('sales_contact', sa.String(), nullable=True),
    sa.Column('partnerships_contact', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('annual_revenue_estimate', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('production_scale', sa.String(), nullable=True),
    sa.Column('global_customers', sa.Integer(), nullable=True),
    sa.Column('us_customers', sa.Integer(), nullable=True),
    sa.Column('main_competitors', sa.JSON(), nullable=True),
    sa.Column('unique_selling_points', sa.JSON(), nullable=True),
    sa.Column('technology_advantages', sa.JSON(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.String(), nullable=True),
    sa.Column('outreach_status', sa.String(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('next_followup_date', sa.DateTime(), nullable=True),
    sa.Column('outreach_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('market_intelligence', sa.JSON(), nullable=True),
    sa.Column('partnership_opportunity', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_companies_company_name'), 'robot_companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_robot_companies_country'), 'robot_companies', ['country'], unique=False)
    op.create_index(op.f('ix_robot_companies_id'), 'robot_companies', ['id'], unique=False)
    op.create_index(op.f('ix_robot_companies_robot_type'), 'robot_companies', ['robot_type'], unique=False)
    op.create_index(op.f('ix_robot_companies_us_presence'), 'robot_companies', ['us_presence'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('robot_type', sa.String(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('payload_capacity_kg', sa.Float(), nullable=True),
    sa.Column('battery_life_hours', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('monthly_lease_usd', sa.Float(), nullable=True),
    sa.Column('roi_stat', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True),
    sa.Column('lead_time_weeks', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_id'), 'robots', ['id'], unique=False)
    op.create_index(op.f('ix_robots_is_active'), 'robots', ['is_active'], unique=False)
    op.create_index(op.f('ix_robots_is_preferred'), 'robots', ['is_preferred'], unique=False)
    op.create_index(op.f('ix_robots_name'), 'robots', ['name'], unique=False)
    op.create_index(op.f('ix_robots_robot_type'), 'robots', ['robot_type'], unique=False)
    op.create_index(op.f('ix_robots_vendor'), 'robots', ['vendor'], unique=False)
    op.create_table('shared_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.String(length=8), nullable=True),
    sa.Column('robot_type', sa.String(length=100), nullable=True),
    sa.Column('robot_cost', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('payback_months', sa.Float(), nullable=True),
    sa.Column('annual_savings', sa.Float(), nullable=True),
    sa.Column('roi_1_year', sa.Float(), nullable=True),
    sa.Column('roi_3_year', sa.Float(), nullable=True),
    sa.Column('total_savings_3_year', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_calculations_id'), 'shared_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_shared_calculations_share_id'), 'shared_calculations', ['share_id'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('automation_score', sa.Float(), nullable=False),
    sa.Column('labor_pain_score', sa.Float(), nullable=False),
    sa.Column('expansion_score', sa.Float(), nullable=False),
    sa.Column('robotics_fit_score', sa.Float(), nullable=False),
    sa.Column('overall_intent_score', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_text', sa.String(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_shared_calculations_share_id'), table_name='shared_calculations')
    op.drop_index(op.f('ix_shared_calculations_id'), table_name='shared_calculations')
    op.drop_table('shared_calculations')
    op.drop_index(op.f('ix_robots_vendor'), table_name='robots')
    op.drop_index(op.f('ix_robots_robot_type'), table_name='robots')
    op.drop_index(op.f('ix_robots_name'), table_name='robots')
    op.drop_index(op.f('ix_robots_is_preferred'), table_name='robots')
    op.drop_index(op.f('ix_robots_is_active'), table_name='robots')
    op.drop_index(op.f('ix_robots_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_robot_companies_us_presence'), table_name='robot_companies')
    op.drop_index(op.f('ix_robot_companies_robot_type'), table_name='robot_companies')
    op.drop_index(op.f('ix_robot_companies_id'), table_name='robot_companies')
    op.drop_index(op.f('ix_robot_companies_country'), table_name='robot_companies')
    op.drop_index(op.f('ix_robot_companies_company_name'), table_name='robot_companies')
    op.drop_table('robot_companies')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
