"""
Seed Robot Library
==================
Populate the robot library with robots from various vendors.
This replaces the hardcoded RichTech-only catalog with a multi-vendor approach.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from app.database import SessionLocal
from app.models.robot import Robot


def seed_robots():
    """Add robots from various vendors to the database."""
    db = SessionLocal()
    
    robots_data = [
        # ── Bear Robotics ──────────────────────────────────────────────────
        {
            "name": "Servi",
            "vendor": "Bear Robotics",
            "tagline": "Food delivery robot for restaurants",
            "description": "Autonomous food running robot that delivers food and clears tables in restaurants. Serves in crowded spaces with 21.6-inch path navigation.",
            "product_url": "https://www.bearrobotics.ai/servi",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality", "Senior Living", "Entertainment"],
            "use_cases": ["Restaurant food runner", "Table clearing", "Drink delivery"],
            "payload_capacity_kg": 30.0,
            "battery_life_hours": 12.0,
            "features": ["3-tier trays", "21.6-inch path navigation", "Obstacle avoidance", "Multi-robot intelligence"],
            "roi_stat": "66-pound load capacity, 12-hour battery, 59M+ deliveries made worldwide",
            "is_active": True,
        },
        {
            "name": "Servi Plus",
            "vendor": "Bear Robotics",
            "tagline": "All-floor navigation delivery robot",
            "description": "Enhanced version with all-floor navigation including ramps and corners. Streamlines service with expanded capacity and 25.6-inch path navigation.",
            "product_url": "https://www.bearrobotics.ai/servi-plus",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality", "Senior Living", "Hotel", "Ghost Kitchen"],
            "use_cases": ["High-volume restaurant service", "Banquet delivery", "Multi-floor service", "Around corners and over ramps"],
            "payload_capacity_kg": 40.0,
            "battery_life_hours": 14.0,
            "features": ["4-tier trays", "All-floor navigation", "Ramp capability", "Corner navigation", "25.6-inch path navigation", "NSF certified", "iF Design Award 2024"],
            "roi_stat": "Expanded capacity for any surface with advanced team robot coordination",
            "is_active": True,
        },
        {
            "name": "Carti 100",
            "vendor": "Bear Robotics",
            "tagline": "Budget-friendly AMR for warehouse automation",
            "description": "Autonomous mobile robot (AMR) for warehouse operations with 100kg payload capacity. Centralized control system (ACS) for multi-robot management.",
            "product_url": "https://www.bearrobotics.ai/carti",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Logistics", "Manufacturing"],
            "use_cases": ["Warehouse automation", "Material transport", "Inventory movement"],
            "payload_capacity_kg": 100.0,
            "features": ["Budget-friendly AMR", "Centralized ACS control", "WMS integration", "Smart device integration", "iF Design Award 2025", "Red Dot Winner 2025"],
            "roi_stat": "Save money and increase efficiency with affordable automation",
            "is_active": True,
        },
        {
            "name": "Carti High Payload",
            "vendor": "Bear Robotics",
            "tagline": "High-capacity warehouse AMR",
            "description": "Heavy-duty autonomous mobile robot for warehouse operations with high payload capacity.",
            "product_url": "https://www.bearrobotics.ai/carti-high-payload",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Logistics", "Manufacturing"],
            "use_cases": ["Heavy material transport", "High-capacity warehouse automation"],
            "features": ["High payload capacity", "Industrial-grade", "ACS integration"],
            "roi_stat": "Handles heavy loads for demanding warehouse operations",
            "is_active": True,
        },
        
        # ── Aethon ─────────────────────────────────────────────────────────
        {
            "name": "TUG",
            "vendor": "Aethon",
            "tagline": "Autonomous hospital delivery robot",
            "description": "Hospital-grade robot for medication, linen, and supply delivery",
            "product_url": "https://www.aethon.com/tug/",
            "robot_type": "logistics",
            "industries": ["Healthcare"],
            "use_cases": ["Medication delivery", "Linen transport", "Lab sample courier", "Waste removal"],
            "payload_capacity_kg": 450.0,
            "battery_life_hours": 10.0,
            "features": ["Secure compartments", "Elevator integration", "HIPAA compliant"],
            "certifications": ["FDA cleared", "UL listed"],
            "roi_stat": "Completes 50+ deliveries/day, freeing nurses for patient care",
            "is_active": True,
        },
        
        # ── Relay Robotics ─────────────────────────────────────────────────
        {
            "name": "Relay",
            "vendor": "Relay Robotics (Savioke)",
            "tagline": "Hotel delivery robot",
            "description": "Autonomous delivery robot for hotels and healthcare",
            "product_url": "https://www.relayrobotics.com/",
            "robot_type": "delivery",
            "industries": ["Hospitality", "Healthcare"],
            "use_cases": ["Hotel amenity delivery", "Towel and toiletry delivery", "Package delivery"],
            "payload_capacity_kg": 13.6,
            "battery_life_hours": 8.0,
            "features": ["Touchscreen interface", "Elevator integration", "Remote monitoring"],
            "roi_stat": "Automates 70% of simple delivery tasks 24/7",
            "is_active": True,
        },
        
        # ── Pudu Robotics ──────────────────────────────────────────────────
        {
            "name": "BellaBot",
            "vendor": "Pudu Robotics",
            "tagline": "Cat-themed food delivery robot",
            "description": "Interactive food delivery robot with distinctive cat ears",
            "product_url": "https://www.pudurobotics.com/product/bellabot",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality"],
            "use_cases": ["Restaurant food delivery", "Dish clearing", "Guest interaction"],
            "payload_capacity_kg": 10.0,
            "battery_life_hours": 9.0,
            "features": ["Interactive cat ears", "Voice prompts", "Multi-tray design"],
            "roi_stat": "Delivers 300+ plates per day with 99.9% navigation success rate",
            "is_active": True,
        },
        {
            "name": "PuduBot 2",
            "vendor": "Pudu Robotics",
            "tagline": "Commercial delivery robot",
            "description": "Versatile delivery robot for multiple industries",
            "product_url": "https://www.pudurobotics.com/product/pudubot2",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality", "Retail", "Healthcare"],
            "use_cases": ["Food delivery", "Hotel service", "Retail fulfillment"],
            "payload_capacity_kg": 50.0,
            "battery_life_hours": 12.0,
            "features": ["Modular trays", "All-terrain wheels", "Cloud management"],
            "roi_stat": "50kg capacity handles diverse delivery needs across industries",
            "is_active": True,
        },
        {
            "name": "KettyBot",
            "vendor": "Pudu Robotics",
            "tagline": "Interactive service robot",
            "description": "Service robot with advertising display and delivery capabilities",
            "product_url": "https://www.pudurobotics.com/product/kettybot",
            "robot_type": "service",
            "industries": ["Food Service", "Retail", "Hospitality"],
            "use_cases": ["Food delivery", "Advertising display", "Customer engagement"],
            "features": ["Built-in screen", "Voice interaction", "Delivery trays"],
            "roi_stat": "Combines delivery and marketing in one platform",
            "is_active": True,
        },
        
        # ── Zebra Technologies ────────────────────────────────────────────
        {
            "name": "Zebra Connect AMR",
            "vendor": "Zebra Technologies",
            "tagline": "Autonomous mobile robots for warehouse automation",
            "description": "CartConnect100 and other AMR solutions for material transport and order fulfillment in warehouses.",
            "product_url": "https://www.zebra.com/us/en/products/autonomous-mobile-robots.html",
            "robot_type": "logistics",
            "industries": ["E-commerce", "Retail", "3PL", "CPG", "Electronics", "Warehousing"],
            "use_cases": ["Cart transport", "Order picking", "Material handling", "Warehouse automation"],
            "features": ["CartConnect100", "Fleet management", "Conveyor integration"],
            "roi_stat": "Streamlines warehouse operations for major logistics providers",
            "is_active": True,
        },
        {
            "name": "Zebra Roller Series",
            "vendor": "Zebra Technologies",
            "tagline": "Conveyor-integrated AMR for tote and bin transfers",
            "description": "Two-model series for seamless integration with conveyor systems for tote and bin transfers.",
            "product_url": "https://www.zebra.com/us/en/products/autonomous-mobile-robots.html",
            "robot_type": "logistics",
            "industries": ["Warehousing", "E-commerce", "3PL"],
            "use_cases": ["Tote transfer", "Bin handling", "Conveyor integration"],
            "features": ["Conveyor integration", "Automated transfers", "2 models available"],
            "roi_stat": "Optimizes tote and bin movement in high-volume facilities",
            "is_active": True,
        },
        {
            "name": "Zebra Flex Series",
            "vendor": "Zebra Technologies",
            "tagline": "Compact AMRs for tight warehouse spaces",
            "description": "Flex Guide and Flex Guide Dual models designed for navigating tight spaces in warehouses.",
            "product_url": "https://www.zebra.com/us/en/products/autonomous-mobile-robots.html",
            "robot_type": "logistics",
            "industries": ["Warehousing", "E-commerce", "Retail"],
            "use_cases": ["Narrow aisle navigation", "Space-constrained picking", "Warehouse automation"],
            "features": ["Flex Guide", "Flex Guide Dual", "Tight space navigation"],
            "roi_stat": "Maximizes efficiency in space-constrained warehouse environments",
            "is_active": True,
        },
        {
            "name": "Zebra Symmetry Fulfillment",
            "vendor": "Zebra Technologies",
            "tagline": "Complete picking solution for warehouses",
            "description": "End-to-end warehouse picking and fulfillment automation solution.",
            "product_url": "https://www.zebra.com/us/en/products/autonomous-mobile-robots.html",
            "robot_type": "logistics",
            "industries": ["E-commerce", "Retail", "3PL"],
            "use_cases": ["Order picking", "Warehouse fulfillment", "Automated picking"],
            "features": ["Complete solution", "Integrated picking", "Fulfillment optimization"],
            "roi_stat": "Complete picking solution for high-volume e-commerce operations",
            "is_active": True,
        },
        
        # ── Brightpick ─────────────────────────────────────────────────────
        {
            "name": "Autopicker",
            "vendor": "Brightpick",
            "tagline": "Multi-purpose warehouse robot with robotic picking",
            "description": "AI-powered warehouse automation robot with robotic picking capability, 24/7 lights-out operation, and SLAM navigation. RaaS subscription model at $1,990/month.",
            "product_url": "https://brightpick.ai/solution/",
            "robot_type": "logistics",
            "industries": ["Warehousing", "E-commerce", "Fulfillment"],
            "use_cases": ["Robotic picking", "Warehouse automation", "Order fulfillment"],
            "price_usd": 1990,
            "features": ["Robotic picking", "SLAM navigation", "24/7 lights-out operation", "AI-powered", "RaaS subscription"],
            "roi_stat": "3-6 months ROI on RaaS model, 1-2 years on CapEx",
            "is_active": True,
        },
        {
            "name": "Giraffe",
            "vendor": "Brightpick",
            "tagline": "Vertical storage robot reaching up to 19 feet",
            "description": "Vertical storage extension system for maximizing warehouse space utilization up to 19 feet high.",
            "product_url": "https://brightpick.ai/solution/",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Fulfillment"],
            "use_cases": ["Vertical storage", "Space optimization", "High-density storage"],
            "features": ["19-foot reach", "Vertical storage", "Space optimization"],
            "roi_stat": "Maximizes vertical warehouse space up to 19 feet",
            "is_active": True,
        },
        {
            "name": "Retriever",
            "vendor": "Brightpick",
            "tagline": "Goods-to-Person operations and sortation robot",
            "description": "Automated goods-to-person solution with integrated sortation capabilities.",
            "product_url": "https://brightpick.ai/solution/",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Fulfillment"],
            "use_cases": ["Goods-to-person", "Sortation", "Order fulfillment"],
            "features": ["Goods-to-person", "Sortation", "Automated retrieval"],
            "roi_stat": "Streamlines goods-to-person and sortation workflows",
            "is_active": True,
        },
        
        # ── Locus Robotics ────────────────────────────────────────────────
        {
            "name": "Locus Origin",
            "vendor": "Locus Robotics",
            "tagline": "Collaborative order fulfillment robot",
            "description": "Part of LocusONE platform. Collaborative robot for warehouse order fulfillment delivering 2x productivity boost.",
            "product_url": "https://locusrobotics.com/locusone/fleet",
            "robot_type": "logistics",
            "industries": ["3PL", "Retail", "eCommerce", "Healthcare", "Industrial"],
            "use_cases": ["Order picking", "Order putaway", "Material transport"],
            "features": ["Collaborative picking", "LocusONE platform", "2x productivity"],
            "roi_stat": "2x productivity boost in order fulfillment operations",
            "is_active": True,
        },
        {
            "name": "Locus Vector",
            "vendor": "Locus Robotics",
            "tagline": "Omnidirectional high-payload AMR",
            "description": "Omnidirectional autonomous mobile robot with high payload capacity for material transport.",
            "product_url": "https://locusrobotics.com/locusone/fleet",
            "robot_type": "logistics",
            "industries": ["Warehousing", "3PL", "Industrial"],
            "use_cases": ["Heavy material transport", "Multi-directional picking", "Warehouse automation"],
            "features": ["Omnidirectional movement", "High payload capacity", "LocusONE integration"],
            "roi_stat": "Omnidirectional movement with high payload for flexible warehouse operations",
            "is_active": True,
        },
        
        # ── Reflex Robotics ───────────────────────────────────────────────
        {
            "name": "Reflex Humanoid",
            "vendor": "Reflex Robotics",
            "tagline": "Affordable humanoid with human-in-the-loop control",
            "description": "General-purpose humanoid robots 20x cheaper than competitors, with human-in-the-loop remote control. Monthly fee model ~2x lower than labor costs. Founded by ex-Boston Dynamics, Tesla, Oculus, ASML engineers. $7M funding from Khosla Ventures.",
            "product_url": "https://www.reflexrobotics.com/",
            "robot_type": "humanoid",
            "industries": ["Manufacturing", "Logistics", "General Purpose"],
            "use_cases": ["General labor automation", "Remote-controlled tasks", "Flexible operations"],
            "features": ["Human-in-the-loop control", "Low-cost humanoid", "Remote operation", "20x cheaper than competitors"],
            "roi_stat": "~2x lower cost than human labor with one-time hardware + monthly fee",
            "is_active": True,
        },
        
        # ── Agility Robotics ──────────────────────────────────────────────
        {
            "name": "Digit",
            "vendor": "Agility Robotics",
            "tagline": "First humanoid robot in production deployment",
            "description": "Market-leading humanoid robot for warehouse and logistics automation. First humanoid in production deployment with proven results. Assembled in Salem, OR with 80% US-sourced parts.",
            "product_url": "https://www.agilityrobotics.com/",
            "robot_type": "humanoid",
            "industries": ["Warehousing", "Logistics", "Manufacturing", "Automotive"],
            "use_cases": ["Warehouse automation", "Logistics operations", "Manufacturing tasks"],
            "features": ["Human-like mobility", "Field-proven deployment", "Safety-focused design", "80% US supply chain", "Arc cloud platform"],
            "roi_stat": "First humanoid in production with commercial agreements including Toyota and Mercado Libre",
            "is_active": True,
        },
        
        # ── Dexterity AI ──────────────────────────────────────────────────
        {
            "name": "Dexterity Robot",
            "vendor": "Dexterity AI",
            "tagline": "Physical AI for warehouse automation",
            "description": "AI-powered robots running full shifts at world's largest logistics companies. Trained with 100M+ autonomous actions. Teams of AI agents give any robot human-like dexterity. Zero safety incidents in production.",
            "product_url": "https://dexterity.ai/",
            "robot_type": "logistics",
            "industries": ["Logistics", "Parcel", "3PL", "Manufacturing"],
            "use_cases": ["Truck unloading", "Truck loading", "Parcel handling", "Warehouse automation"],
            "features": ["Foresight world model", "100M+ training actions", "AI agent teams", "Human-like dexterity", "<400ms decision speed"],
            "roi_stat": "100M+ autonomous decisions in production with zero safety incidents",
            "is_active": True,
        },
        
        # ── Figure AI ─────────────────────────────────────────────────────
        {
            "name": "Figure 03",
            "vendor": "Figure AI",
            "tagline": "General purpose humanoid for everyday home help",
            "description": "Human-shaped AI-powered humanoid robot for household tasks. Powered by Helix AI for navigating unpredictable home environments. Over 100 years of combined AI & humanoid experience on team.",
            "product_url": "https://www.figure.ai/",
            "robot_type": "humanoid",
            "industries": ["Home Automation", "General Purpose"],
            "use_cases": ["Household tasks", "Home help", "General assistance"],
            "features": ["Helix AI", "Human-shaped design", "Home environment navigation", "AI-powered"],
            "roi_stat": "Handles household tasks like humans do with AI navigation",
            "is_active": True,
        },
        
        # ── GreyOrange ────────────────────────────────────────────────────
        {
            "name": "GreyMatter",
            "vendor": "GreyOrange",
            "tagline": "Warehouse orchestration platform with multi-agent AI",
            "description": "Warehouse orchestration across people, robots and systems delivering 1M+ optimizations per minute. Vendor-agnostic platform managing 100,000+ physical agents worldwide. #1 in multi-agent, cross-domain AI orchestration (Gartner recognized).",
            "product_url": "https://www.greyorange.com/greymatter/",
            "robot_type": "software",
            "industries": ["Warehousing", "E-commerce", "Retail", "3PL"],
            "use_cases": ["Warehouse orchestration", "Multi-agent coordination", "Fleet management"],
            "features": ["1M+ optimizations/min", "Vendor-agnostic", "100K+ agents worldwide", "Gartner recognized", "Real-time orchestration"],
            "roi_stat": "2-4x warehouse productivity, 45% lower fulfillment cost, 99%+ inventory accuracy",
            "is_active": True,
        },
        {
            "name": "gStore",
            "vendor": "GreyOrange",
            "tagline": "Real-time RFID inventory for retail stores",
            "description": "In-store RFID inventory precision with automatic replenishment and AI-driven shopper insights. 98% inventory accuracy, 5-20% sales lift.",
            "product_url": "https://www.greyorange.com/gstore/",
            "robot_type": "software",
            "industries": ["Retail", "Fashion", "Apparel"],
            "use_cases": ["Inventory management", "Store operations", "Omnichannel retail"],
            "features": ["RFID precision", "Automatic replenishment", "AI insights", "98% accuracy"],
            "roi_stat": "98% inventory accuracy, 5-20% in-store sales lift, 50% fewer order cancellations",
            "is_active": True,
        },
        
        # ── Simbe Robotics ───────────────────────────────────────────────
        {
            "name": "Tally",
            "vendor": "Simbe Robotics",
            "tagline": "World's first fully autonomous inventory robot",
            "description": "Autonomous inventory robot with advanced computer vision for retail shelf auditing. Scans every aisle and location every day with multimodal data capture.",
            "product_url": "https://www.simberobotics.com/",
            "robot_type": "service",
            "industries": ["Retail", "Grocery", "Supermarket"],
            "use_cases": ["Inventory auditing", "Price tag verification", "Planogram compliance", "On-shelf availability"],
            "features": ["Advanced computer vision", "Autonomous navigation", "Daily store audits", "Real-time alerts"],
            "roi_stat": "98% on-shelf availability, 90% better price accuracy, 50hrs/wk rededicated to shoppers",
            "is_active": True,
        },
        {
            "name": "Tally Spot",
            "vendor": "Simbe Robotics",
            "tagline": "Fixed sensors for high-turnover areas",
            "description": "Stationary sensors that monitor high-turnover and high-risk retail areas with continuous data capture.",
            "product_url": "https://www.simberobotics.com/store-intelligence/tally-spot",
            "robot_type": "service",
            "industries": ["Retail", "Grocery"],
            "use_cases": ["High-turnover monitoring", "Checkout area monitoring", "Continuous inventory tracking"],
            "features": ["Fixed sensor", "Continuous monitoring", "High-turnover focus"],
            "roi_stat": "Monitors critical areas for immediate restocking",
            "is_active": True,
        },
        {
            "name": "Tally RFID",
            "vendor": "Simbe Robotics",
            "tagline": "Advanced RFID sensors for apparel and soft goods",
            "description": "Specialized RFID-enabled robot designed for apparel, fashion, and soft goods inventory management.",
            "product_url": "https://www.simberobotics.com/store-intelligence/tally-rfid",
            "robot_type": "service",
            "industries": ["Retail", "Fashion", "Apparel"],
            "use_cases": ["Apparel inventory", "Soft goods tracking", "Fashion retail"],
            "features": ["Advanced RFID", "Apparel-specific", "Soft goods optimized"],
            "roi_stat": "Optimized for fashion and apparel inventory precision",
            "is_active": True,
        },
        
        # ── FORTNA ────────────────────────────────────────────────────────
        # Note: FORTNA is primarily a systems integrator/solutions provider, not a robot manufacturer
        # They work with AGVs, AMRs, ASRS, and other automation but don't make proprietary robots
        # Including their warehouse execution system software
        {
            "name": "FORTNA WES",
            "vendor": "FORTNA",
            "tagline": "Warehouse execution system for optimization",
            "description": "Intelligent warehouse execution software optimizing real-time dynamic operational performance. Vendor-agnostic platform for maximizing DC operations visibility and control.",
            "product_url": "https://www.fortna.com/software/wes/",
            "robot_type": "software",
            "industries": ["Warehousing", "Logistics", "E-commerce", "3PL", "Retail"],
            "use_cases": ["Warehouse optimization", "Real-time operations", "DC management"],
            "features": ["Real-time optimization", "Vendor-agnostic", "Dynamic performance", "Visibility and control"],
            "roi_stat": "Optimizes warehouse operations with vendor-agnostic automation control",
            "is_active": True,
        },
        
        # ── Xenex ──────────────────────────────────────────────────────────
        {
            "name": "LightStrike",
            "vendor": "Xenex",
            "tagline": "UV-C disinfection robot",
            "description": "Pulsed xenon UV disinfection robot for healthcare",
            "product_url": "https://www.xenex.com/",
            "robot_type": "disinfection",
            "industries": ["Healthcare", "Hospitality"],
            "use_cases": ["Hospital room disinfection", "OR cleaning", "Isolation room sanitization"],
            "features": ["Pulsed xenon UV", "360-degree coverage", "Remote monitoring"],
            "certifications": ["FDA cleared"],
            "roi_stat": "Reduces HAIs by up to 50%, disinfects room in 5-15 minutes",
            "is_active": True,
        },
        
        # ── UVD Robots ─────────────────────────────────────────────────────
        {
            "name": "UVD Robot",
            "vendor": "UVD Robots (Blue Ocean Robotics)",
            "tagline": "Autonomous UV-C disinfection",
            "description": "Mobile UV-C disinfection robot for healthcare and public spaces",
            "product_url": "https://www.uvd-robots.com/",
            "robot_type": "disinfection",
            "industries": ["Healthcare", "Hospitality", "Retail"],
            "use_cases": ["Room disinfection", "Corridor sanitization", "Operating room cleaning"],
            "features": ["Autonomous navigation", "UV-C lamps", "Safety sensors"],
            "roi_stat": "Eliminates 99.99% of pathogens in 10 minutes per room",
            "is_active": True,
        },
        
        # ── Geek+ ──────────────────────────────────────────────────────────
        {
            "name": "PopPick (P-Series)",
            "vendor": "Geek+",
            "tagline": "Shelf-to-person goods-to-person picking",
            "description": "Mobile robots bring shelves directly to operators to reduce walking and speed up picks. Most flexible G2P picking system. #1 AMR leader for 7 consecutive years.",
            "product_url": "https://www.geekplus.com/solutions/shelf-to-person",
            "robot_type": "logistics",
            "industries": ["3PL", "Retail", "E-commerce", "Apparel", "Grocery", "Pharma"],
            "use_cases": ["Order picking", "Warehouse automation", "Goods-to-person"],
            "payload_capacity_kg": 800.0,
            "features": ["Shelf-to-person", "Autonomous navigation", "WES platform", "850+ warehouses deployed"],
            "roi_stat": "400% productivity increase, 1-3 year ROI, 10B+ orders fulfilled",
            "is_active": True,
        },
        {
            "name": "RoboShuttle (RS-Series)",
            "vendor": "Geek+",
            "tagline": "High-bay tote-to-person system",
            "description": "Robots retrieve totes from high-bay racks (11m) and deliver them to workstations at high speed. High-density G2P picking.",
            "product_url": "https://www.geekplus.com/solutions/tote-to-person",
            "robot_type": "logistics",
            "industries": ["Warehousing", "E-commerce", "3PL"],
            "use_cases": ["Tote retrieval", "High-density storage", "Fast picking"],
            "features": ["11m high-bay reach", "High-speed retrieval", "Dense storage"],
            "roi_stat": "30% storage improvement, 350k items/day processing",
            "is_active": True,
        },
        {
            "name": "Skycube (X-Series)",
            "vendor": "Geek+",
            "tagline": "Multilevel pallet ASRS and picking",
            "description": "Supports both pallet storage & retrieval and piece picking within the same storage structure (up to 21m height).",
            "product_url": "https://www.geekplus.com/solutions/pallet-to-person",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Manufacturing", "Distribution"],
            "use_cases": ["Pallet storage", "Pallet retrieval", "Piece picking"],
            "features": ["21m height capability", "Dual function", "ASRS integration"],
            "roi_stat": "Combines pallet storage and picking in single system up to 21m",
            "is_active": True,
        },
        {
            "name": "Sorting Robot (S-Series)",
            "vendor": "Geek+",
            "tagline": "Dynamic parcel and SKU sorting",
            "description": "Robots sort items dynamically based on order logic and fulfillment needs. Parcel, SKU, or order line sorting with full flexibility.",
            "product_url": "https://www.geekplus.com/solutions/sorting",
            "robot_type": "logistics",
            "industries": ["E-commerce", "Parcel", "3PL"],
            "use_cases": ["Parcel sorting", "SKU sorting", "Order sortation"],
            "features": ["Dynamic sorting", "Flexible logic", "High throughput"],
            "roi_stat": "Full flexibility in parcel, SKU, and order line sorting",
            "is_active": True,
        },
        {
            "name": "Forklift Robot (F-Series)",
            "vendor": "Geek+",
            "tagline": "Autonomous forklift for material handling",
            "description": "Automated forklift robots for pallet transport, staging, and material flow management.",
            "product_url": "https://www.geekplus.com/technology/f-series-robots",
            "robot_type": "logistics",
            "industries": ["Warehousing", "Manufacturing", "Distribution"],
            "use_cases": ["Pallet transport", "Material staging", "Intralogistics"],
            "features": ["Autonomous forklift", "Pallet handling", "Fleet coordination"],
            "roi_stat": "Automates pallet transport and staging operations",
            "is_active": True,
        },
        
        # ── Knightscope ───────────────────────────────────────────────────
        {
            "name": "K5",
            "vendor": "Knightscope",
            "tagline": "Autonomous security robot for outdoor patrol",
            "description": "AI-driven 24/7 autonomous security robot that patrols commercial properties and public spaces. Mobile perimeter protection with intelligent eyes, ears and voice. NASDAQ: KSCP.",
            "product_url": "https://www.knightscope.com/products/k5",
            "robot_type": "security",
            "industries": ["Corporate Campus", "Retail", "Logistics", "Healthcare", "Education", "Public Safety"],
            "use_cases": ["Perimeter patrol", "Physical deterrence", "24/7 monitoring"],
            "features": ["360° HD video", "Thermal imaging", "License plate recognition", "Two-way audio", "KSOC monitoring"],
            "price_usd": 245000,
            "roi_stat": "24/7 autonomous patrol with AI-driven threat detection",
            "is_active": True,
        },
        {
            "name": "K7",
            "vendor": "Knightscope",
            "tagline": "All-terrain autonomous security robot",
            "description": "Engineered for real-world outdoor environments. Built to deter, detect, and report with greater visibility and intelligence for expanded patrol coverage.",
            "product_url": "https://www.knightscope.com/k7",
            "robot_type": "security",
            "industries": ["Corporate Campus", "Industrial", "Public Safety", "Logistics"],
            "use_cases": ["Outdoor patrol", "Rough terrain monitoring", "Perimeter security"],
            "features": ["All-terrain capability", "Advanced sensors", "Autonomous patrol", "Weather-resistant"],
            "roi_stat": "Covers more terrain with all-weather patrol capability",
            "is_active": True,
        },
        {
            "name": "K1 Hemisphere",
            "vendor": "Knightscope",
            "tagline": "Stationary automated security device",
            "description": "Automated security in a stationary, fully featured and remotely monitored device. Premium appearance with versatile mounting for strategic locations.",
            "product_url": "https://www.knightscope.com/products/k1-hemisphere",
            "robot_type": "security",
            "industries": ["Retail", "Banking", "Hospitality", "Corporate"],
            "use_cases": ["ATM vestibule monitoring", "EV charging station security", "Hallway surveillance", "Warehouse monitoring"],
            "features": ["Stationary monitoring", "Remote access", "Multiple mounting options", "Premium design"],
            "price_usd": 70000,
            "roi_stat": "Strategic fixed-position monitoring for high-risk areas",
            "is_active": True,
        },
        {
            "name": "K1 Blue Light Tower",
            "vendor": "Knightscope",
            "tagline": "Emergency communication with priority wireless",
            "description": "Emergency help on demand with one-button priority wireless communication powered by Verizon Frontline. For campuses, universities, healthcare, parking structures.",
            "product_url": "https://www.knightscope.com/products/k1-blue-light-tower",
            "robot_type": "emergency",
            "industries": ["Education", "Healthcare", "Corporate Campus", "Public Sector"],
            "use_cases": ["Emergency calls", "Campus safety", "Parking lot security"],
            "features": ["One-button emergency", "Verizon Frontline network", "Blue light visibility", "Two-way audio"],
            "roi_stat": "Priority emergency communication where help is needed most",
            "is_active": True,
        },
        {
            "name": "Automated Gunshot Detection (AGD)",
            "vendor": "Knightscope",
            "tagline": "Instant gunshot detection and localization",
            "description": "Detects gunshots and delivers immediate notifications with point of origin accurate within 2 meters within 2 seconds. Integrates with cameras and access control.",
            "product_url": "https://www.knightscope.com/products/agd",
            "robot_type": "security",
            "industries": ["Education", "Healthcare", "Corporate Campus", "Public Safety"],
            "use_cases": ["Gunshot detection", "Active shooter response", "Campus safety"],
            "features": ["<2 second detection", "2 meter accuracy", "Camera integration", "Access control sync"],
            "roi_stat": "Know precisely when and where shots fired within 2 seconds",
            "is_active": True,
        },
        
        # ── MiR (Mobile Industrial Robots) ────────────────────────────────
        {
            "name": "MiR100",
            "vendor": "MiR (Mobile Industrial Robots)",
            "tagline": "Entry-level collaborative AMR",
            "description": "Compact autonomous mobile robot for material transport in manufacturing and logistics. Payload up to 100kg. Part of Teradyne automation portfolio.",
            "product_url": "https://www.mir-robots.com/",
            "robot_type": "logistics",
            "industries": ["Manufacturing", "Logistics", "Healthcare"],
            "use_cases": ["Material transport", "Parts delivery", "Internal logistics"],
            "payload_capacity_kg": 100.0,
            "features": ["Collaborative safety", "3D cameras", "Fleet management", "Easy programming"],
            "roi_stat": "Safe collaborative transport up to 100kg payload",
            "is_active": True,
        },
        {
            "name": "MiR250",
            "vendor": "MiR (Mobile Industrial Robots)",
            "tagline": "Mid-capacity industrial AMR",
            "description": "Versatile AMR for heavier loads in manufacturing environments. 250kg payload capacity with advanced navigation.",
            "product_url": "https://www.mir-robots.com/",
            "robot_type": "logistics",
            "industries": ["Manufacturing", "Automotive", "Electronics"],
            "use_cases": ["Heavy material transport", "Assembly line logistics", "Warehouse operations"],
            "payload_capacity_kg": 250.0,
            "features": ["250kg capacity", "Narrow aisle navigation", "Modular top modules"],
            "roi_stat": "Heavy-duty transport with 250kg payload capacity",
            "is_active": True,
        },
        {
            "name": "MiR600",
            "vendor": "MiR (Mobile Industrial Robots)",
            "tagline": "Heavy payload industrial AMR",
            "description": "High-capacity autonomous mobile robot for pallet and heavy load transport. 600kg payload for industrial applications.",
            "product_url": "https://www.mir-robots.com/",
            "robot_type": "logistics",
            "industries": ["Manufacturing", "Automotive", "Warehousing"],
            "use_cases": ["Pallet transport", "Heavy load handling", "Cross-docking"],
            "payload_capacity_kg": 600.0,
            "features": ["600kg payload", "Pallet handling", "Industrial grade"],
            "roi_stat": "Industrial-strength pallet transport up to 600kg",
            "is_active": True,
        },
        {
            "name": "MiR1200",
            "vendor": "MiR (Mobile Industrial Robots)",
            "tagline": "Maximum capacity pallet AMR",
            "description": "Largest MiR robot for heaviest industrial loads. 1200kg payload capacity for demanding manufacturing and logistics operations.",
            "product_url": "https://www.mir-robots.com/",
            "robot_type": "logistics",
            "industries": ["Manufacturing", "Heavy Industry", "Automotive"],
            "use_cases": ["Heavy pallet transport", "Large part handling", "Industrial logistics"],
            "payload_capacity_kg": 1200.0,
            "features": ["1200kg payload", "Maximum capacity", "Robust design", "Pallet jack integration"],
            "roi_stat": "Maximum 1200kg payload for heaviest industrial applications",
            "is_active": True,
        },
        
        # ── AutoStore ──────────────────────────────────────────────────────
        {
            "name": "AutoStore System",
            "vendor": "AutoStore",
            "tagline": "Cubic warehouse automation storage system",
            "description": "Grid-based cubic storage automation with robots retrieving bins from dense storage. 1,150+ systems worldwide, revolutionizing warehouse efficiency with 75% space savings.",
            "product_url": "https://www.autostore.com/",
            "robot_type": "logistics",
            "industries": ["E-commerce", "Retail", "Grocery", "3PL"],
            "use_cases": ["High-density storage", "Order fulfillment", "Goods-to-person"],
            "features": ["Cubic grid storage", "75% space savings", "Modular expansion", "1,150+ global installations"],
            "roi_stat": "75% space savings with 1,150+ systems deployed globally",
            "is_active": True,
        },
        
        # ── Keenon Robotics ───────────────────────────────────────────────
        {
            "name": "DINERBOT",
            "vendor": "Keenon Robotics",
            "tagline": "Premium food delivery robot",
            "description": "Leading food service robot in Asian markets. High-capacity multi-tray delivery for restaurants with advanced navigation and customer interaction.",
            "product_url": "https://www.keenonrobot.com/",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality"],
            "use_cases": ["Restaurant delivery", "Food running", "Table service"],
            "features": ["Multi-tray capacity", "Voice interaction", "Elevator integration"],
            "roi_stat": "Market leader in Asia with thousands of deployments",
            "is_active": True,
        },
        {
            "name": "PEANUT",
            "vendor": "Keenon Robotics",
            "tagline": "Compact delivery robot",
            "description": "Smaller profile food delivery robot for tight restaurant spaces. Popular in cafes and quick-service restaurants.",
            "product_url": "https://www.keenonrobot.com/",
            "robot_type": "delivery",
            "industries": ["Food Service", "Hospitality"],
            "use_cases": ["Cafe delivery", "Quick-service restaurants", "Small venue service"],
            "features": ["Compact design", "Narrow aisle navigation", "Cost-effective"],
            "roi_stat": "Compact solution for space-constrained food service venues",
            "is_active": True,
        },
        
        # ── Richtech Robotics (migrated from hardcoded) ────────────────────
        {
            "name": "MATRADEE",
            "vendor": "Richtech Robotics",
            "tagline": "Autonomous food & amenity delivery",
            "product_url": "https://www.richtechrobotics.com/matradee",
            "robot_type": "delivery",
            "industries": ["Hospitality", "Food Service"],
            "use_cases": ["In-room dining delivery", "Restaurant food runner", "Floor-to-floor room service"],
            "roi_stat": "Handles 400+ daily deliveries, reducing delivery labor by 40%",
            "is_active": True,
            "is_preferred": False,
        },
        {
            "name": "MATRADEE X",
            "vendor": "Richtech Robotics",
            "tagline": "High-capacity food & cargo delivery",
            "product_url": "https://www.richtechrobotics.com/matradee-x",
            "robot_type": "delivery",
            "industries": ["Hospitality", "Food Service"],
            "use_cases": ["Large-tray banquet delivery", "High-volume restaurant service", "Multi-stop room service"],
            "roi_stat": "Larger payload capacity for peak-hour banquet and catering operations",
            "is_active": True,
            "is_preferred": False,
        },
        {
            "name": "ADAM",
            "vendor": "Richtech Robotics",
            "tagline": "Autonomous bar & F&B robot",
            "product_url": "https://www.richtechrobotics.com/adam",
            "robot_type": "bartender",
            "industries": ["Hospitality", "Food Service"],
            "use_cases": ["Bar & cocktail service", "Coffee & beverage automation", "Event drink service"],
            "roi_stat": "Consistent pour accuracy, operates 18+ hours without breaks",
            "is_active": True,
            "is_preferred": False,
        },
        {
            "name": "LUCKI",
            "vendor": "Richtech Robotics",
            "tagline": "Delivery robot with secured drawers",
            "product_url": "https://www.richtechrobotics.com/lucki",
            "robot_type": "delivery",
            "industries": ["Healthcare", "Hospitality", "Logistics"],
            "use_cases": ["Pharmacy & medication delivery", "Secure document/supply transport", "Back-of-house logistics"],
            "roi_stat": "Secure multi-compartment delivery — ideal for sensitive items like medications",
            "is_active": True,
        },
        {
            "name": "MEDBOT",
            "vendor": "Richtech Robotics",
            "tagline": "Hospital-grade autonomous delivery robot",
            "product_url": "https://www.richtechrobotics.com/medbot",
            "robot_type": "logistics",
            "industries": ["Healthcare"],
            "use_cases": ["Medication delivery to patient rooms", "Linen & supply transport", "Lab sample courier"],
            "roi_stat": "200+ deliveries/day per unit; frees nursing staff for direct patient care",
            "is_active": True,
        },
        {
            "name": "DUST-E MX",
            "vendor": "Richtech Robotics",
            "tagline": "Autonomous UV-C disinfection robot",
            "product_url": "https://www.richtechrobotics.com/dust-e-mx",
            "robot_type": "disinfection",
            "industries": ["Healthcare", "Hospitality", "Food Service"],
            "use_cases": ["Hospital room & corridor disinfection", "Hotel room turnover sanitation", "Food prep area sterilization"],
            "roi_stat": "Disinfects a standard room in <10 minutes; reduces HAI risk by up to 97.7%",
            "is_active": True,
            "is_preferred": False,
        },
        {
            "name": "AIDY",
            "vendor": "Richtech Robotics",
            "tagline": "Guest-facing indoor delivery robot",
            "product_url": "https://www.richtechrobotics.com/aidy",
            "robot_type": "delivery",
            "industries": ["Hospitality"],
            "use_cases": ["Hotel amenity delivery", "Package & parcel delivery", "Concierge fulfillment"],
            "roi_stat": "Automates up to 80% of standard concierge delivery tasks 24/7",
            "is_active": True,
        },
    ]
    
    # Create tables if they don't exist
    from app.database import Base, engine
    Base.metadata.create_all(bind=engine)
    
    # Clear existing robots (if any)
    try:
        db.query(Robot).delete()
    except:
        pass  # Table might not exist yet
    
    # Add all robots
    for robot_data in robots_data:
        robot = Robot(**robot_data)
        db.add(robot)
    
    db.commit()
    
    # Print summary
    total = db.query(Robot).count()
    vendors = db.query(Robot.vendor).distinct().count()
    
    print(f"\n✅ Robot library seeded successfully!")
    print(f"   Total robots: {total}")
    print(f"   Vendors: {vendors}")
    print(f"\n   Vendors in library:")
    for vendor in db.query(Robot.vendor).distinct().all():
        count = db.query(Robot).filter(Robot.vendor == vendor[0]).count()
        print(f"   - {vendor[0]}: {count} robots")
    
    db.close()


if __name__ == "__main__":
    seed_robots()
